-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.24-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table orders.accounts_financial
CREATE TABLE IF NOT EXISTS `accounts_financial` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `person_id` int(20) NOT NULL,
  `creditor` int(11) NOT NULL,
  `debtor` int(11) NOT NULL,
  `cause` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `FK_accounts_financial_persons_accounts_financial` (`person_id`),
  CONSTRAINT `FK_accounts_financial_persons_accounts_financial` FOREIGN KEY (`person_id`) REFERENCES `persons_accounts_financial` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.accounts_financial: ~2 rows (approximately)
INSERT INTO `accounts_financial` (`id`, `person_id`, `creditor`, `debtor`, `cause`, `created_at`) VALUES
	(4, 2, 30, 0, '*', '2022-12-20 22:19:07'),
	(5, 2, 0, 30, '*', '2022-12-20 22:21:56');

-- Dumping structure for table orders.account_stament_agents
CREATE TABLE IF NOT EXISTS `account_stament_agents` (
  `id` int(50) NOT NULL AUTO_INCREMENT,
  `agent_id` int(20) NOT NULL,
  `payed` int(20) NOT NULL,
  `total` int(20) NOT NULL,
  `late` int(20) NOT NULL,
  `excel` char(255) DEFAULT NULL,
  `user_id` int(20) DEFAULT NULL,
  `confirm` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `FK_account_stament_agents_users` (`agent_id`),
  KEY `FK_account_stament_agents_users_2` (`user_id`),
  CONSTRAINT `FK_account_stament_agents_users` FOREIGN KEY (`agent_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_account_stament_agents_users_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.account_stament_agents: ~0 rows (approximately)
INSERT INTO `account_stament_agents` (`id`, `agent_id`, `payed`, `total`, `late`, `excel`, `user_id`, `confirm`, `created_at`, `updated_at`) VALUES
	(32, 28, 850, 850, 0, 'محمود طرفايه/32تقفيل محمود طرفايه 32.xlsx', 27, 0, '2022-12-19 23:27:51', '2022-12-20 10:05:08'),
	(33, 28, 340, 340, 0, 'محمود طرفايه/33تقفيل محمود طرفايه 33.xlsx', 27, 0, '2022-12-21 15:40:27', '2022-12-21 15:40:27');

-- Dumping structure for table orders.account_stament_companies
CREATE TABLE IF NOT EXISTS `account_stament_companies` (
  `id` int(50) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `company_id` int(20) NOT NULL,
  `payed` int(20) NOT NULL,
  `total` int(20) NOT NULL,
  `late` int(20) NOT NULL,
  `excel` char(255) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_account_stament_companies_companies` (`company_id`),
  CONSTRAINT `FK_account_stament_companies_companies` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.account_stament_companies: ~0 rows (approximately)
INSERT INTO `account_stament_companies` (`id`, `created_at`, `company_id`, `payed`, `total`, `late`, `excel`) VALUES
	(42, '2022-12-19 23:29:38', 4, 800, 800, 0, 'ADM/42تقفيل ADM 42.xlsx');

-- Dumping structure for table orders.causes_return
CREATE TABLE IF NOT EXISTS `causes_return` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `cause` char(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.causes_return: ~1 rows (approximately)
INSERT INTO `causes_return` (`id`, `cause`) VALUES
	(1, 'لم يتم التعيين');

-- Dumping structure for table orders.causes_return_history
CREATE TABLE IF NOT EXISTS `causes_return_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `causes_return_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.causes_return_history: ~0 rows (approximately)

-- Dumping structure for table orders.centers
CREATE TABLE IF NOT EXISTS `centers` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `center_name` char(50) NOT NULL,
  `governate_id` int(11) DEFAULT NULL,
  `id_agent` int(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_centers_users` (`id_agent`),
  KEY `FK_centers_governorates` (`governate_id`),
  CONSTRAINT `FK_centers_governorates` FOREIGN KEY (`governate_id`) REFERENCES `governorates` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_centers_users` FOREIGN KEY (`id_agent`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.centers: ~7 rows (approximately)
INSERT INTO `centers` (`id`, `center_name`, `governate_id`, `id_agent`) VALUES
	(6, 'كيمان', 7, 32),
	(7, 'باغوص', 7, 33),
	(8, 'مسله', 7, 34),
	(9, 'ابشواي', 7, 28),
	(10, 'اطسا', 7, 29),
	(11, 'سنورس', 7, 31),
	(12, 'طاميه', 7, 30);

-- Dumping structure for table orders.centers_history
CREATE TABLE IF NOT EXISTS `centers_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `centers_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.centers_history: ~0 rows (approximately)

-- Dumping structure for table orders.chats
CREATE TABLE IF NOT EXISTS `chats` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `msg` int(11) NOT NULL,
  `state` int(11) NOT NULL,
  `reciver_id` int(20) NOT NULL,
  `sender_id` int(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_chats_users` (`reciver_id`),
  KEY `FK_chats_users_2` (`sender_id`),
  CONSTRAINT `FK_chats_users` FOREIGN KEY (`reciver_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_chats_users_2` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.chats: ~0 rows (approximately)

-- Dumping structure for table orders.cities
CREATE TABLE IF NOT EXISTS `cities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `governorate_id` int(11) NOT NULL,
  `city_name_ar` varchar(200) NOT NULL,
  `city_name_en` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=397 DEFAULT CHARSET=utf8;

-- Dumping data for table orders.cities: 396 rows
/*!40000 ALTER TABLE `cities` DISABLE KEYS */;
INSERT INTO `cities` (`id`, `governorate_id`, `city_name_ar`, `city_name_en`) VALUES
	(1, 1, '15 مايو', '15 May'),
	(2, 1, 'الازبكية', 'Al Azbakeyah'),
	(3, 1, 'البساتين', 'Al Basatin'),
	(4, 1, 'التبين', 'Tebin'),
	(5, 1, 'الخليفة', 'El-Khalifa'),
	(6, 1, 'الدراسة', 'El darrasa'),
	(7, 1, 'الدرب الاحمر', 'Aldarb Alahmar'),
	(8, 1, 'الزاوية الحمراء', 'Zawya al-Hamra'),
	(9, 1, 'الزيتون', 'El-Zaytoun'),
	(10, 1, 'الساحل', 'Sahel'),
	(11, 1, 'السلام', 'El Salam'),
	(12, 1, 'السيدة زينب', 'Sayeda Zeinab'),
	(13, 1, 'الشرابية', 'El Sharabeya'),
	(14, 1, 'مدينة الشروق', 'Shorouk'),
	(15, 1, 'الظاهر', 'El Daher'),
	(16, 1, 'العتبة', 'Ataba'),
	(17, 1, 'القاهرة الجديدة', 'New Cairo'),
	(18, 1, 'المرج', 'El Marg'),
	(19, 1, 'عزبة النخل', 'Ezbet el Nakhl'),
	(20, 1, 'المطرية', 'Matareya'),
	(21, 1, 'المعادى', 'Maadi'),
	(22, 1, 'المعصرة', 'Maasara'),
	(23, 1, 'المقطم', 'Mokattam'),
	(24, 1, 'المنيل', 'Manyal'),
	(25, 1, 'الموسكى', 'Mosky'),
	(26, 1, 'النزهة', 'Nozha'),
	(27, 1, 'الوايلى', 'Waily'),
	(28, 1, 'باب الشعرية', 'Bab al-Shereia'),
	(29, 1, 'بولاق', 'Bolaq'),
	(30, 1, 'جاردن سيتى', 'Garden City'),
	(31, 1, 'حدائق القبة', 'Hadayek El-Kobba'),
	(32, 1, 'حلوان', 'Helwan'),
	(33, 1, 'دار السلام', 'Dar Al Salam'),
	(34, 1, 'شبرا', 'Shubra'),
	(35, 1, 'طره', 'Tura'),
	(36, 1, 'عابدين', 'Abdeen'),
	(37, 1, 'عباسية', 'Abaseya'),
	(38, 1, 'عين شمس', 'Ain Shams'),
	(39, 1, 'مدينة نصر', 'Nasr City'),
	(40, 1, 'مصر الجديدة', 'New Heliopolis'),
	(41, 1, 'مصر القديمة', 'Masr Al Qadima'),
	(42, 1, 'منشية ناصر', 'Mansheya Nasir'),
	(43, 1, 'مدينة بدر', 'Badr City'),
	(44, 1, 'مدينة العبور', 'Obour City'),
	(45, 1, 'وسط البلد', 'Cairo Downtown'),
	(46, 1, 'الزمالك', 'Zamalek'),
	(47, 1, 'قصر النيل', 'Kasr El Nile'),
	(48, 1, 'الرحاب', 'Rehab'),
	(49, 1, 'القطامية', 'Katameya'),
	(50, 1, 'مدينتي', 'Madinty'),
	(51, 1, 'روض الفرج', 'Rod Alfarag'),
	(52, 1, 'شيراتون', 'Sheraton'),
	(53, 1, 'الجمالية', 'El-Gamaleya'),
	(54, 1, 'العاشر من رمضان', '10th of Ramadan City'),
	(55, 1, 'الحلمية', 'Helmeyat Alzaytoun'),
	(56, 1, 'النزهة الجديدة', 'New Nozha'),
	(57, 1, 'العاصمة الإدارية', 'Capital New'),
	(58, 2, 'الجيزة', 'Giza'),
	(59, 2, 'السادس من أكتوبر', 'Sixth of October'),
	(60, 2, 'الشيخ زايد', 'Cheikh Zayed'),
	(61, 2, 'الحوامدية', 'Hawamdiyah'),
	(62, 2, 'البدرشين', 'Al Badrasheen'),
	(63, 2, 'الصف', 'Saf'),
	(64, 2, 'أطفيح', 'Atfih'),
	(65, 2, 'العياط', 'Al Ayat'),
	(66, 2, 'الباويطي', 'Al-Bawaiti'),
	(67, 2, 'منشأة القناطر', 'ManshiyetAl Qanater'),
	(68, 2, 'أوسيم', 'Oaseem'),
	(69, 2, 'كرداسة', 'Kerdasa'),
	(70, 2, 'أبو النمرس', 'Abu Nomros'),
	(71, 2, 'كفر غطاطي', 'Kafr Ghati'),
	(72, 2, 'منشأة البكاري', 'Manshiyet Al Bakari'),
	(73, 2, 'الدقى', 'Dokki'),
	(74, 2, 'العجوزة', 'Agouza'),
	(75, 2, 'الهرم', 'Haram'),
	(76, 2, 'الوراق', 'Warraq'),
	(77, 2, 'امبابة', 'Imbaba'),
	(78, 2, 'بولاق الدكرور', 'Boulaq Dakrour'),
	(79, 2, 'الواحات البحرية', 'Al Wahat Al Baharia'),
	(80, 2, 'العمرانية', 'Omraneya'),
	(81, 2, 'المنيب', 'Moneeb'),
	(82, 2, 'بين السرايات', 'Bin Alsarayat'),
	(83, 2, 'الكيت كات', 'Kit Kat'),
	(84, 2, 'المهندسين', 'Mohandessin'),
	(85, 2, 'فيصل', 'Faisal'),
	(86, 2, 'أبو رواش', 'Abu Rawash'),
	(87, 2, 'حدائق الأهرام', 'Hadayek Alahram'),
	(88, 2, 'الحرانية', 'Haraneya'),
	(89, 2, 'حدائق اكتوبر', 'Hadayek October'),
	(90, 2, 'صفط اللبن', 'Saft Allaban'),
	(91, 2, 'القرية الذكية', 'Smart Village'),
	(92, 2, 'ارض اللواء', 'Ard Ellwaa'),
	(93, 3, 'ابو قير', 'Abu Qir'),
	(94, 3, 'الابراهيمية', 'Al Ibrahimeyah'),
	(95, 3, 'الأزاريطة', 'Azarita'),
	(96, 3, 'الانفوشى', 'Anfoushi'),
	(97, 3, 'الدخيلة', 'Dekheila'),
	(98, 3, 'السيوف', 'El Soyof'),
	(99, 3, 'العامرية', 'Ameria'),
	(100, 3, 'اللبان', 'El Labban'),
	(101, 3, 'المفروزة', 'Al Mafrouza'),
	(102, 3, 'المنتزه', 'El Montaza'),
	(103, 3, 'المنشية', 'Mansheya'),
	(104, 3, 'الناصرية', 'Naseria'),
	(105, 3, 'امبروزو', 'Ambrozo'),
	(106, 3, 'باب شرق', 'Bab Sharq'),
	(107, 3, 'برج العرب', 'Bourj Alarab'),
	(108, 3, 'ستانلى', 'Stanley'),
	(109, 3, 'سموحة', 'Smouha'),
	(110, 3, 'سيدى بشر', 'Sidi Bishr'),
	(111, 3, 'شدس', 'Shads'),
	(112, 3, 'غيط العنب', 'Gheet Alenab'),
	(113, 3, 'فلمينج', 'Fleming'),
	(114, 3, 'فيكتوريا', 'Victoria'),
	(115, 3, 'كامب شيزار', 'Camp Shizar'),
	(116, 3, 'كرموز', 'Karmooz'),
	(117, 3, 'محطة الرمل', 'Mahta Alraml'),
	(118, 3, 'مينا البصل', 'Mina El-Basal'),
	(119, 3, 'العصافرة', 'Asafra'),
	(120, 3, 'العجمي', 'Agamy'),
	(121, 3, 'بكوس', 'Bakos'),
	(122, 3, 'بولكلي', 'Boulkly'),
	(123, 3, 'كليوباترا', 'Cleopatra'),
	(124, 3, 'جليم', 'Glim'),
	(125, 3, 'المعمورة', 'Al Mamurah'),
	(126, 3, 'المندرة', 'Al Mandara'),
	(127, 3, 'محرم بك', 'Moharam Bek'),
	(128, 3, 'الشاطبي', 'Elshatby'),
	(129, 3, 'سيدي جابر', 'Sidi Gaber'),
	(130, 3, 'الساحل الشمالي', 'North Coast/sahel'),
	(131, 3, 'الحضرة', 'Alhadra'),
	(132, 3, 'العطارين', 'Alattarin'),
	(133, 3, 'سيدي كرير', 'Sidi Kerir'),
	(134, 3, 'الجمرك', 'Elgomrok'),
	(135, 3, 'المكس', 'Al Max'),
	(136, 3, 'مارينا', 'Marina'),
	(137, 4, 'المنصورة', 'Mansoura'),
	(138, 4, 'طلخا', 'Talkha'),
	(139, 4, 'ميت غمر', 'Mitt Ghamr'),
	(140, 4, 'دكرنس', 'Dekernes'),
	(141, 4, 'أجا', 'Aga'),
	(142, 4, 'منية النصر', 'Menia El Nasr'),
	(143, 4, 'السنبلاوين', 'Sinbillawin'),
	(144, 4, 'الكردي', 'El Kurdi'),
	(145, 4, 'بني عبيد', 'Bani Ubaid'),
	(146, 4, 'المنزلة', 'Al Manzala'),
	(147, 4, 'تمي الأمديد', 'tami al\'amdid'),
	(148, 4, 'الجمالية', 'aljamalia'),
	(149, 4, 'شربين', 'Sherbin'),
	(150, 4, 'المطرية', 'Mataria'),
	(151, 4, 'بلقاس', 'Belqas'),
	(152, 4, 'ميت سلسيل', 'Meet Salsil'),
	(153, 4, 'جمصة', 'Gamasa'),
	(154, 4, 'محلة دمنة', 'Mahalat Damana'),
	(155, 4, 'نبروه', 'Nabroh'),
	(156, 5, 'الغردقة', 'Hurghada'),
	(157, 5, 'رأس غارب', 'Ras Ghareb'),
	(158, 5, 'سفاجا', 'Safaga'),
	(159, 5, 'القصير', 'El Qusiar'),
	(160, 5, 'مرسى علم', 'Marsa Alam'),
	(161, 5, 'الشلاتين', 'Shalatin'),
	(162, 5, 'حلايب', 'Halaib'),
	(163, 5, 'الدهار', 'Aldahar'),
	(164, 6, 'دمنهور', 'Damanhour'),
	(165, 6, 'كفر الدوار', 'Kafr El Dawar'),
	(166, 6, 'رشيد', 'Rashid'),
	(167, 6, 'إدكو', 'Edco'),
	(168, 6, 'أبو المطامير', 'Abu al-Matamir'),
	(169, 6, 'أبو حمص', 'Abu Homs'),
	(170, 6, 'الدلنجات', 'Delengat'),
	(171, 6, 'المحمودية', 'Mahmoudiyah'),
	(172, 6, 'الرحمانية', 'Rahmaniyah'),
	(173, 6, 'إيتاي البارود', 'Itai Baroud'),
	(174, 6, 'حوش عيسى', 'Housh Eissa'),
	(175, 6, 'شبراخيت', 'Shubrakhit'),
	(176, 6, 'كوم حمادة', 'Kom Hamada'),
	(177, 6, 'بدر', 'Badr'),
	(178, 6, 'وادي النطرون', 'Wadi Natrun'),
	(179, 6, 'النوبارية الجديدة', 'New Nubaria'),
	(180, 6, 'النوبارية', 'Alnoubareya'),
	(181, 7, 'الفيوم', 'Fayoum'),
	(182, 7, 'الفيوم الجديدة', 'Fayoum El Gedida'),
	(183, 7, 'طامية', 'Tamiya'),
	(184, 7, 'سنورس', 'Snores'),
	(185, 7, 'إطسا', 'Etsa'),
	(186, 7, 'إبشواي', 'Epschway'),
	(187, 7, 'يوسف الصديق', 'Yusuf El Sediaq'),
	(188, 7, 'الحادقة', 'Hadqa'),
	(189, 7, 'اطسا', 'Atsa'),
	(190, 7, 'الجامعة', 'Algamaa'),
	(191, 7, 'السيالة', 'Sayala'),
	(192, 8, 'طنطا', 'Tanta'),
	(193, 8, 'المحلة الكبرى', 'Al Mahalla Al Kobra'),
	(194, 8, 'كفر الزيات', 'Kafr El Zayat'),
	(195, 8, 'زفتى', 'Zefta'),
	(196, 8, 'السنطة', 'El Santa'),
	(197, 8, 'قطور', 'Qutour'),
	(198, 8, 'بسيون', 'Basion'),
	(199, 8, 'سمنود', 'Samannoud'),
	(200, 9, 'الإسماعيلية', 'Ismailia'),
	(201, 9, 'فايد', 'Fayed'),
	(202, 9, 'القنطرة شرق', 'Qantara Sharq'),
	(203, 9, 'القنطرة غرب', 'Qantara Gharb'),
	(204, 9, 'التل الكبير', 'El Tal El Kabier'),
	(205, 9, 'أبو صوير', 'Abu Sawir'),
	(206, 9, 'القصاصين الجديدة', 'Kasasien El Gedida'),
	(207, 9, 'نفيشة', 'Nefesha'),
	(208, 9, 'الشيخ زايد', 'Sheikh Zayed'),
	(209, 10, 'شبين الكوم', 'Shbeen El Koom'),
	(210, 10, 'مدينة السادات', 'Sadat City'),
	(211, 10, 'منوف', 'Menouf'),
	(212, 10, 'سرس الليان', 'Sars El-Layan'),
	(213, 10, 'أشمون', 'Ashmon'),
	(214, 10, 'الباجور', 'Al Bagor'),
	(215, 10, 'قويسنا', 'Quesna'),
	(216, 10, 'بركة السبع', 'Berkat El Saba'),
	(217, 10, 'تلا', 'Tala'),
	(218, 10, 'الشهداء', 'Al Shohada'),
	(219, 11, 'المنيا', 'Minya'),
	(220, 11, 'المنيا الجديدة', 'Minya El Gedida'),
	(221, 11, 'العدوة', 'El Adwa'),
	(222, 11, 'مغاغة', 'Magagha'),
	(223, 11, 'بني مزار', 'Bani Mazar'),
	(224, 11, 'مطاي', 'Mattay'),
	(225, 11, 'سمالوط', 'Samalut'),
	(226, 11, 'المدينة الفكرية', 'Madinat El Fekria'),
	(227, 11, 'ملوي', 'Meloy'),
	(228, 11, 'دير مواس', 'Deir Mawas'),
	(229, 11, 'ابو قرقاص', 'Abu Qurqas'),
	(230, 11, 'ارض سلطان', 'Ard Sultan'),
	(231, 12, 'بنها', 'Banha'),
	(232, 12, 'قليوب', 'Qalyub'),
	(233, 12, 'شبرا الخيمة', 'Shubra Al Khaimah'),
	(234, 12, 'القناطر الخيرية', 'Al Qanater Charity'),
	(235, 12, 'الخانكة', 'Khanka'),
	(236, 12, 'كفر شكر', 'Kafr Shukr'),
	(237, 12, 'طوخ', 'Tukh'),
	(238, 12, 'قها', 'Qaha'),
	(239, 12, 'العبور', 'Obour'),
	(240, 12, 'الخصوص', 'Khosous'),
	(241, 12, 'شبين القناطر', 'Shibin Al Qanater'),
	(242, 12, 'مسطرد', 'Mostorod'),
	(243, 13, 'الخارجة', 'El Kharga'),
	(244, 13, 'باريس', 'Paris'),
	(245, 13, 'موط', 'Mout'),
	(246, 13, 'الفرافرة', 'Farafra'),
	(247, 13, 'بلاط', 'Balat'),
	(248, 13, 'الداخلة', 'Dakhla'),
	(249, 14, 'السويس', 'Suez'),
	(250, 14, 'الجناين', 'Alganayen'),
	(251, 14, 'عتاقة', 'Ataqah'),
	(252, 14, 'العين السخنة', 'Ain Sokhna'),
	(253, 14, 'فيصل', 'Faysal'),
	(254, 15, 'أسوان', 'Aswan'),
	(255, 15, 'أسوان الجديدة', 'Aswan El Gedida'),
	(256, 15, 'دراو', 'Drau'),
	(257, 15, 'كوم أمبو', 'Kom Ombo'),
	(258, 15, 'نصر النوبة', 'Nasr Al Nuba'),
	(259, 15, 'كلابشة', 'Kalabsha'),
	(260, 15, 'إدفو', 'Edfu'),
	(261, 15, 'الرديسية', 'Al-Radisiyah'),
	(262, 15, 'البصيلية', 'Al Basilia'),
	(263, 15, 'السباعية', 'Al Sibaeia'),
	(264, 15, 'ابوسمبل السياحية', 'Abo Simbl Al Siyahia'),
	(265, 15, 'مرسى علم', 'Marsa Alam'),
	(266, 16, 'أسيوط', 'Assiut'),
	(267, 16, 'أسيوط الجديدة', 'Assiut El Gedida'),
	(268, 16, 'ديروط', 'Dayrout'),
	(269, 16, 'منفلوط', 'Manfalut'),
	(270, 16, 'القوصية', 'Qusiya'),
	(271, 16, 'أبنوب', 'Abnoub'),
	(272, 16, 'أبو تيج', 'Abu Tig'),
	(273, 16, 'الغنايم', 'El Ghanaim'),
	(274, 16, 'ساحل سليم', 'Sahel Selim'),
	(275, 16, 'البداري', 'El Badari'),
	(276, 16, 'صدفا', 'Sidfa'),
	(277, 17, 'بني سويف', 'Bani Sweif'),
	(278, 17, 'بني سويف الجديدة', 'Beni Suef El Gedida'),
	(279, 17, 'الواسطى', 'Al Wasta'),
	(280, 17, 'ناصر', 'Naser'),
	(281, 17, 'إهناسيا', 'Ehnasia'),
	(282, 17, 'ببا', 'beba'),
	(283, 17, 'الفشن', 'Fashn'),
	(284, 17, 'سمسطا', 'Somasta'),
	(285, 17, 'الاباصيرى', 'Alabbaseri'),
	(286, 17, 'مقبل', 'Mokbel'),
	(287, 18, 'بورسعيد', 'PorSaid'),
	(288, 18, 'بورفؤاد', 'Port Fouad'),
	(289, 18, 'العرب', 'Alarab'),
	(290, 18, 'حى الزهور', 'Zohour'),
	(291, 18, 'حى الشرق', 'Alsharq'),
	(292, 18, 'حى الضواحى', 'Aldawahi'),
	(293, 18, 'حى المناخ', 'Almanakh'),
	(294, 18, 'حى مبارك', 'Mubarak'),
	(295, 19, 'دمياط', 'Damietta'),
	(296, 19, 'دمياط الجديدة', 'New Damietta'),
	(297, 19, 'رأس البر', 'Ras El Bar'),
	(298, 19, 'فارسكور', 'Faraskour'),
	(299, 19, 'الزرقا', 'Zarqa'),
	(300, 19, 'السرو', 'alsaru'),
	(301, 19, 'الروضة', 'alruwda'),
	(302, 19, 'كفر البطيخ', 'Kafr El-Batikh'),
	(303, 19, 'عزبة البرج', 'Azbet Al Burg'),
	(304, 19, 'ميت أبو غالب', 'Meet Abou Ghalib'),
	(305, 19, 'كفر سعد', 'Kafr Saad'),
	(306, 20, 'الزقازيق', 'Zagazig'),
	(307, 20, 'العاشر من رمضان', 'Al Ashr Men Ramadan'),
	(308, 20, 'منيا القمح', 'Minya Al Qamh'),
	(309, 20, 'بلبيس', 'Belbeis'),
	(310, 20, 'مشتول السوق', 'Mashtoul El Souq'),
	(311, 20, 'القنايات', 'Qenaiat'),
	(312, 20, 'أبو حماد', 'Abu Hammad'),
	(313, 20, 'القرين', 'El Qurain'),
	(314, 20, 'ههيا', 'Hehia'),
	(315, 20, 'أبو كبير', 'Abu Kabir'),
	(316, 20, 'فاقوس', 'Faccus'),
	(317, 20, 'الصالحية الجديدة', 'El Salihia El Gedida'),
	(318, 20, 'الإبراهيمية', 'Al Ibrahimiyah'),
	(319, 20, 'ديرب نجم', 'Deirb Negm'),
	(320, 20, 'كفر صقر', 'Kafr Saqr'),
	(321, 20, 'أولاد صقر', 'Awlad Saqr'),
	(322, 20, 'الحسينية', 'Husseiniya'),
	(323, 20, 'صان الحجر القبلية', 'san alhajar alqablia'),
	(324, 20, 'منشأة أبو عمر', 'Manshayat Abu Omar'),
	(325, 21, 'الطور', 'Al Toor'),
	(326, 21, 'شرم الشيخ', 'Sharm El-Shaikh'),
	(327, 21, 'دهب', 'Dahab'),
	(328, 21, 'نويبع', 'Nuweiba'),
	(329, 21, 'طابا', 'Taba'),
	(330, 21, 'سانت كاترين', 'Saint Catherine'),
	(331, 21, 'أبو رديس', 'Abu Redis'),
	(332, 21, 'أبو زنيمة', 'Abu Zenaima'),
	(333, 21, 'رأس سدر', 'Ras Sidr'),
	(334, 22, 'كفر الشيخ', 'Kafr El Sheikh'),
	(335, 22, 'وسط البلد كفر الشيخ', 'Kafr El Sheikh Downtown'),
	(336, 22, 'دسوق', 'Desouq'),
	(337, 22, 'فوه', 'Fooh'),
	(338, 22, 'مطوبس', 'Metobas'),
	(339, 22, 'برج البرلس', 'Burg Al Burullus'),
	(340, 22, 'بلطيم', 'Baltim'),
	(341, 22, 'مصيف بلطيم', 'Masief Baltim'),
	(342, 22, 'الحامول', 'Hamol'),
	(343, 22, 'بيلا', 'Bella'),
	(344, 22, 'الرياض', 'Riyadh'),
	(345, 22, 'سيدي سالم', 'Sidi Salm'),
	(346, 22, 'قلين', 'Qellen'),
	(347, 22, 'سيدي غازي', 'Sidi Ghazi'),
	(348, 23, 'مرسى مطروح', 'Marsa Matrouh'),
	(349, 23, 'الحمام', 'El Hamam'),
	(350, 23, 'العلمين', 'Alamein'),
	(351, 23, 'الضبعة', 'Dabaa'),
	(352, 23, 'النجيلة', 'Al-Nagila'),
	(353, 23, 'سيدي براني', 'Sidi Brani'),
	(354, 23, 'السلوم', 'Salloum'),
	(355, 23, 'سيوة', 'Siwa'),
	(356, 23, 'مارينا', 'Marina'),
	(357, 23, 'الساحل الشمالى', 'North Coast'),
	(358, 24, 'الأقصر', 'Luxor'),
	(359, 24, 'الأقصر الجديدة', 'New Luxor'),
	(360, 24, 'إسنا', 'Esna'),
	(361, 24, 'طيبة الجديدة', 'New Tiba'),
	(362, 24, 'الزينية', 'Al ziynia'),
	(363, 24, 'البياضية', 'Al Bayadieh'),
	(364, 24, 'القرنة', 'Al Qarna'),
	(365, 24, 'أرمنت', 'Armant'),
	(366, 24, 'الطود', 'Al Tud'),
	(367, 25, 'قنا', 'Qena'),
	(368, 25, 'قنا الجديدة', 'New Qena'),
	(369, 25, 'ابو طشت', 'Abu Tesht'),
	(370, 25, 'نجع حمادي', 'Nag Hammadi'),
	(371, 25, 'دشنا', 'Deshna'),
	(372, 25, 'الوقف', 'Alwaqf'),
	(373, 25, 'قفط', 'Qaft'),
	(374, 25, 'نقادة', 'Naqada'),
	(375, 25, 'فرشوط', 'Farshout'),
	(376, 25, 'قوص', 'Quos'),
	(377, 26, 'العريش', 'Arish'),
	(378, 26, 'الشيخ زويد', 'Sheikh Zowaid'),
	(379, 26, 'نخل', 'Nakhl'),
	(380, 26, 'رفح', 'Rafah'),
	(381, 26, 'بئر العبد', 'Bir al-Abed'),
	(382, 26, 'الحسنة', 'Al Hasana'),
	(383, 27, 'سوهاج', 'Sohag'),
	(384, 27, 'سوهاج الجديدة', 'Sohag El Gedida'),
	(385, 27, 'أخميم', 'Akhmeem'),
	(386, 27, 'أخميم الجديدة', 'Akhmim El Gedida'),
	(387, 27, 'البلينا', 'Albalina'),
	(388, 27, 'المراغة', 'El Maragha'),
	(389, 27, 'المنشأة', 'almunsha\'a'),
	(390, 27, 'دار السلام', 'Dar AISalaam'),
	(391, 27, 'جرجا', 'Gerga'),
	(392, 27, 'جهينة الغربية', 'Jahina Al Gharbia'),
	(393, 27, 'ساقلته', 'Saqilatuh'),
	(394, 27, 'طما', 'Tama'),
	(395, 27, 'طهطا', 'Tahta'),
	(396, 27, 'الكوثر', 'Alkawthar');
/*!40000 ALTER TABLE `cities` ENABLE KEYS */;

-- Dumping structure for table orders.companies
CREATE TABLE IF NOT EXISTS `companies` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `name` char(50) NOT NULL,
  `special_intructions` varchar(255) DEFAULT NULL,
  `commission` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.companies: ~1 rows (approximately)
INSERT INTO `companies` (`id`, `name`, `special_intructions`, `commission`) VALUES
	(4, 'ADM', 'نتتايتاتي', 20),
	(5, 'Eagle', NULL, 22);

-- Dumping structure for table orders.companies_history
CREATE TABLE IF NOT EXISTS `companies_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `companies_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.companies_history: ~0 rows (approximately)

-- Dumping structure for table orders.companies_phones
CREATE TABLE IF NOT EXISTS `companies_phones` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `note_en` char(50) NOT NULL,
  `note_ar` char(50) NOT NULL,
  `phone_number` char(11) NOT NULL,
  `id_companiy` int(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_companies_phones_companies` (`id_companiy`),
  CONSTRAINT `FK_companies_phones_companies` FOREIGN KEY (`id_companiy`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.companies_phones: ~2 rows (approximately)
INSERT INTO `companies_phones` (`id`, `note_en`, `note_ar`, `phone_number`, `id_companiy`) VALUES
	(5, 'fhjghkjkj', 'سيبيسب', '01148422820', 4),
	(6, 'sdfddf', 'سيبيسب11', '01140481692', 4);

-- Dumping structure for table orders.companies_phones_history
CREATE TABLE IF NOT EXISTS `companies_phones_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `companies_phones_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.companies_phones_history: ~0 rows (approximately)

-- Dumping structure for table orders.company_expenses
CREATE TABLE IF NOT EXISTS `company_expenses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` char(50) NOT NULL,
  `cost` int(11) NOT NULL,
  `type_out` tinyint(1) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.company_expenses: ~0 rows (approximately)
INSERT INTO `company_expenses` (`id`, `name`, `cost`, `type_out`, `created_at`) VALUES
	(3, 'بعبوص', 1000, 0, '2022-12-19 23:34:02'),
	(4, 'فايبال', 70, 0, '2022-12-19 23:57:56');

-- Dumping structure for table orders.delegates
CREATE TABLE IF NOT EXISTS `delegates` (
  `id_center` int(11) NOT NULL,
  `delegate_id` int(20) NOT NULL,
  KEY `id_center` (`id_center`),
  KEY `FK_delegates_users` (`delegate_id`),
  CONSTRAINT `FK_delegates_users` FOREIGN KEY (`delegate_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.delegates: ~0 rows (approximately)

-- Dumping structure for table orders.discounts
CREATE TABLE IF NOT EXISTS `discounts` (
  `id` int(40) unsigned NOT NULL AUTO_INCREMENT,
  `cost` int(5) unsigned NOT NULL,
  `id_user` int(20) DEFAULT NULL,
  `notes` char(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `FK_discounts_users` (`id_user`),
  CONSTRAINT `FK_discounts_users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.discounts: ~4 rows (approximately)
INSERT INTO `discounts` (`id`, `cost`, `id_user`, `notes`, `created_at`) VALUES
	(1, 30, 26, '', '2022-12-19 17:06:15'),
	(2, 6, 26, 'fghtrghgf', '2022-12-01 01:42:03'),
	(3, 90, 26, 'test -', '2022-12-19 17:06:11'),
	(4, 70, 26, '5646', '2022-12-19 17:06:05');

-- Dumping structure for table orders.failed_jobs
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table orders.failed_jobs: ~0 rows (approximately)

-- Dumping structure for table orders.governorates
CREATE TABLE IF NOT EXISTS `governorates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `governorate_name_ar` varchar(50) NOT NULL,
  `governorate_name_en` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8;

-- Dumping data for table orders.governorates: ~27 rows (approximately)
INSERT INTO `governorates` (`id`, `governorate_name_ar`, `governorate_name_en`) VALUES
	(1, 'القاهرة', 'Cairo'),
	(2, 'الجيزة', 'Giza'),
	(3, 'الأسكندرية', 'Alexandria'),
	(4, 'الدقهلية', 'Dakahlia'),
	(5, 'البحر الأحمر', 'Red Sea'),
	(6, 'البحيرة', 'Beheira'),
	(7, 'الفيوم', 'Fayoum'),
	(8, 'الغربية', 'Gharbiya'),
	(9, 'الإسماعلية', 'Ismailia'),
	(10, 'المنوفية', 'Menofia'),
	(11, 'المنيا', 'Minya'),
	(12, 'القليوبية', 'Qaliubiya'),
	(13, 'الوادي الجديد', 'New Valley'),
	(14, 'السويس', 'Suez'),
	(15, 'اسوان', 'Aswan'),
	(16, 'اسيوط', 'Assiut'),
	(17, 'بني سويف', 'Beni Suef'),
	(18, 'بورسعيد', 'Port Said'),
	(19, 'دمياط', 'Damietta'),
	(20, 'الشرقية', 'Sharkia'),
	(21, 'جنوب سيناء', 'South Sinai'),
	(22, 'كفر الشيخ', 'Kafr Al sheikh'),
	(23, 'مطروح', 'Matrouh'),
	(24, 'الأقصر', 'Luxor'),
	(25, 'قنا', 'Qena'),
	(26, 'شمال سيناء', 'North Sinai'),
	(27, 'سوهاج', 'Sohag');

-- Dumping structure for table orders.keep_money
CREATE TABLE IF NOT EXISTS `keep_money` (
  `id` int(90) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `moneyold` int(11) DEFAULT 0,
  `moneyafter` int(11) NOT NULL,
  `user_id` int(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_keep_money_users` (`user_id`),
  CONSTRAINT `FK_keep_money_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.keep_money: ~8 rows (approximately)
INSERT INTO `keep_money` (`id`, `created_at`, `moneyold`, `moneyafter`, `user_id`) VALUES
	(8, '2022-12-19 18:12:06', 0, 0, 26),
	(17, '2022-12-19 23:28:56', 0, 850, 27),
	(18, '2022-12-19 23:29:39', 850, 50, 27),
	(19, '2022-12-19 23:32:29', 50, -1400, 27),
	(20, '2022-12-19 23:34:02', -1400, -2400, 27),
	(21, '2022-12-19 23:57:56', -2400, -2470, 27),
	(22, '2022-12-20 21:32:13', -2470, -2470, 27),
	(23, '2022-12-20 22:19:07', -2470, -2500, 27),
	(24, '2022-12-20 22:21:56', -2500, -2470, 27),
	(25, '2022-12-27 00:38:14', -2470, -2390, 27);

-- Dumping structure for table orders.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table orders.migrations: ~2 rows (approximately)
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2019_08_19_000000_create_failed_jobs_table', 1),
	(2, '2019_12_14_000001_create_personal_access_tokens_table', 1);

-- Dumping structure for table orders.notifications
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` int(11) NOT NULL,
  `msg` int(11) NOT NULL,
  `state` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_notifications_users` (`user_id`),
  CONSTRAINT `FK_notifications_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.notifications: ~0 rows (approximately)

-- Dumping structure for table orders.orders
CREATE TABLE IF NOT EXISTS `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_company` int(20) DEFAULT NULL COMMENT 'required',
  `id_police` char(20) DEFAULT NULL COMMENT 'required',
  `name_client` char(250) DEFAULT NULL COMMENT 'required',
  `phone` char(50) DEFAULT NULL COMMENT 'required',
  `phone2` char(50) DEFAULT NULL,
  `center_id` int(20) DEFAULT NULL,
  `agent_id` int(20) DEFAULT NULL COMMENT 'required',
  `delegate_id` int(20) DEFAULT NULL,
  `address` char(255) DEFAULT NULL COMMENT 'required',
  `cost` char(50) DEFAULT '0' COMMENT 'required',
  `salary_charge` char(50) DEFAULT NULL,
  `date` date DEFAULT NULL COMMENT 'required',
  `notes` char(255) DEFAULT NULL,
  `special_intructions` char(255) DEFAULT NULL,
  `special_intructions2` char(255) DEFAULT NULL,
  `name_product` char(255) DEFAULT NULL,
  `sender` char(50) DEFAULT NULL,
  `weghit` char(50) DEFAULT NULL,
  `open` char(250) DEFAULT NULL,
  `status_id` int(20) DEFAULT NULL,
  `cause_id` int(20) DEFAULT NULL,
  `order_locate` tinyint(1) DEFAULT 0 COMMENT '0=>not deliver ,1=>incompany,2=>withdelegate,3=>return',
  `gps_delivered` char(50) DEFAULT NULL,
  `identy_number` char(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `delegate_supply` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0=>not ,1=>yes',
  `delegate_supply_date` timestamp NULL DEFAULT NULL,
  `company_supply` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0=>not ,1=>yes',
  `company_supply_date` timestamp NULL DEFAULT NULL,
  `on_archieve` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `FK_orders_centers` (`center_id`),
  KEY `FK_orders_companies` (`id_company`),
  KEY `FK_orders_order_state` (`status_id`),
  KEY `FK_orders_causes_return` (`cause_id`),
  KEY `FK_orders_users_2` (`agent_id`),
  KEY `FK_orders_users` (`delegate_id`),
  CONSTRAINT `FK_orders_causes_return` FOREIGN KEY (`cause_id`) REFERENCES `causes_return` (`id`),
  CONSTRAINT `FK_orders_centers` FOREIGN KEY (`center_id`) REFERENCES `centers` (`id`),
  CONSTRAINT `FK_orders_companies` FOREIGN KEY (`id_company`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_orders_order_state` FOREIGN KEY (`status_id`) REFERENCES `order_state` (`id`),
  CONSTRAINT `FK_orders_users` FOREIGN KEY (`delegate_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_orders_users_2` FOREIGN KEY (`agent_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1401 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.orders: ~9 rows (approximately)
INSERT INTO `orders` (`id`, `id_company`, `id_police`, `name_client`, `phone`, `phone2`, `center_id`, `agent_id`, `delegate_id`, `address`, `cost`, `salary_charge`, `date`, `notes`, `special_intructions`, `special_intructions2`, `name_product`, `sender`, `weghit`, `open`, `status_id`, `cause_id`, `order_locate`, `gps_delivered`, `identy_number`, `created_at`, `updated_at`, `delegate_supply`, `delegate_supply_date`, `company_supply`, `company_supply_date`, `on_archieve`) VALUES
	(1305, 4, '9861810', 'ماجده يوسف امين', '1221767840', 'none', 9, 29, 27, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 22:04:16', 1, '2022-12-21 15:40:27', 0, '2022-12-19 23:29:39', 0),
	(1306, 4, '27212915', 'Noura emaghraby', '1027212915', 'none', 9, 29, 27, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 1, 1, 1, '', 'none', '2022-12-19 18:06:52', '2022-12-26 22:05:27', 1, '2022-12-21 15:40:27', 0, '2022-12-19 23:29:39', 0),
	(1307, 4, '3294168', 'نيهاد صبري', '1000410022', 'none', 9, 28, 27, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', NULL, 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 22:39:09', 1, '2022-12-21 15:40:27', 0, '2022-12-19 23:29:39', 0),
	(1308, 4, '9861777', 'ادم محمد', '1149719466', 'none', 9, 28, NULL, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', NULL, 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 21:54:46', 1, '2022-12-21 15:40:27', 0, '2022-12-19 23:29:39', 0),
	(1309, 4, '18612', 'عائشه قطب', '1067042079', 'none', 9, 30, NULL, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', NULL, 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 21:54:46', 0, '2022-12-19 23:27:51', 0, '2022-12-19 23:29:39', 0),
	(1310, 4, '34475', 'حمدي العوام', '1092213667', 'none', 9, 30, NULL, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', NULL, 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 21:54:46', 0, '2022-12-19 23:27:51', 0, '2022-12-19 23:29:39', 0),
	(1311, 4, '4', 'بلال عدلي محمد', '1069451190', 'none', 9, 30, NULL, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', NULL, 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 21:54:46', 0, '2022-12-19 23:27:51', 0, '2022-12-19 23:29:39', 0),
	(1312, 4, '95835', 'عصام صلاح', '1091318240', 'none', 9, 30, NULL, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', NULL, 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 21:54:46', 0, '2022-12-19 23:27:51', 0, '2022-12-19 23:29:39', 0),
	(1399, 4, '34475', 'حمدي العوام', '1092213667', 'none', 9, 30, NULL, 'العجميين', '100', 'none', '1999-12-30', 'none', 'none', NULL, 'none', 'none', 'none', 'none', 1, 1, 1, NULL, 'none', '2022-12-19 18:06:52', '2022-12-26 21:54:46', 0, '2022-12-19 23:27:51', 0, '2022-12-19 23:29:39', 0);

-- Dumping structure for table orders.orders_history
CREATE TABLE IF NOT EXISTS `orders_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `orders_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.orders_history: ~0 rows (approximately)

-- Dumping structure for table orders.order_state
CREATE TABLE IF NOT EXISTS `order_state` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `state` char(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.order_state: ~9 rows (approximately)
INSERT INTO `order_state` (`id`, `state`) VALUES
	(1, 'تم التسليم'),
	(2, 'تم التسليم جزئي'),
	(3, 'مرتجع'),
	(4, 'مرتجع بقيمه'),
	(5, 'مرتجع بعموله'),
	(6, 'محاوله اخرى'),
	(7, 'تم الاستبدال'),
	(8, 'تم السحب'),
	(10, 'لم يتم التحديد بعد');

-- Dumping structure for table orders.order_state_history
CREATE TABLE IF NOT EXISTS `order_state_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `order_state_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.order_state_history: ~0 rows (approximately)

-- Dumping structure for table orders.personal_access_tokens
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  UNIQUE KEY `tokenable_id` (`tokenable_id`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table orders.personal_access_tokens: ~0 rows (approximately)

-- Dumping structure for table orders.persons_accounts_financial
CREATE TABLE IF NOT EXISTS `persons_accounts_financial` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `rank` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.persons_accounts_financial: ~2 rows (approximately)
INSERT INTO `persons_accounts_financial` (`id`, `name`, `rank`, `created_at`, `updated_at`) VALUES
	(2, 'mahmoud medhat', 'fdfdgg', '2022-12-20 21:27:57', NULL);

-- Dumping structure for table orders.persons_accounts_financial_history
CREATE TABLE IF NOT EXISTS `persons_accounts_financial_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `persons_accounts_financial_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.persons_accounts_financial_history: ~0 rows (approximately)

-- Dumping structure for table orders.profits
CREATE TABLE IF NOT EXISTS `profits` (
  `id` int(90) NOT NULL AUTO_INCREMENT,
  `moneyold` int(11) DEFAULT NULL,
  `moneyafter` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.profits: ~0 rows (approximately)
INSERT INTO `profits` (`id`, `moneyold`, `moneyafter`, `created_at`) VALUES
	(12, NULL, 0, '2022-12-20 09:38:13'),
	(13, -2470, 80, '2022-12-27 00:38:15');

-- Dumping structure for table orders.profits_out
CREATE TABLE IF NOT EXISTS `profits_out` (
  `id` int(90) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `moneyold` int(11) DEFAULT NULL,
  `moneyafter` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  KEY `id` (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.profits_out: ~4 rows (approximately)
INSERT INTO `profits_out` (`id`, `name`, `moneyold`, `moneyafter`, `created_at`) VALUES
	(1, '', NULL, 0, '2022-12-19 18:14:07'),
	(2, '', 0, 0, '2022-12-19 22:45:48'),
	(8, '', 0, 50, '2022-12-19 23:29:39'),
	(12, 'mahmoud', -2470, 130, '2022-12-27 00:38:15');

-- Dumping structure for table orders.ranks
CREATE TABLE IF NOT EXISTS `ranks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` char(18) NOT NULL,
  `name_ar` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.ranks: ~9 rows (approximately)
INSERT INTO `ranks` (`id`, `name`, `name_ar`) VALUES
	(1, 'admin', 'مشرف'),
	(2, 'customer service', 'خدمه عملاء'),
	(3, 'operations', 'اوبريشن'),
	(4, 'data entry', 'مدخل بيانات'),
	(5, 'acountant', 'محاسب'),
	(6, 'employer', 'موظف'),
	(7, 'company', 'شركه'),
	(8, 'agent', 'وكيل'),
	(9, 'representative', 'مندوب');

-- Dumping structure for table orders.salaries
CREATE TABLE IF NOT EXISTS `salaries` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `id_user` int(20) DEFAULT NULL,
  `salary` int(11) NOT NULL,
  `discount` int(11) DEFAULT NULL,
  `notes` char(250) DEFAULT NULL,
  `done` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0=>not,1=>done',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `FK_salaries_users` (`id_user`),
  CONSTRAINT `FK_salaries_users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.salaries: ~2 rows (approximately)
INSERT INTO `salaries` (`id`, `id_user`, `salary`, `discount`, `notes`, `done`, `created_at`, `updated_at`) VALUES
	(1, 26, 1500, 50, NULL, 1, '2022-12-01 01:42:03', '2022-12-01 01:42:03'),
	(2, NULL, 9000, 260, NULL, 0, '2022-12-18 17:06:34', '2022-12-18 17:06:34');

-- Dumping structure for table orders.stocks
CREATE TABLE IF NOT EXISTS `stocks` (
  `id` int(11) NOT NULL,
  `quantitiy` int(11) NOT NULL,
  `name` int(11) NOT NULL,
  `size` int(11) NOT NULL,
  `color` int(11) NOT NULL,
  `company_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_stocks_companies` (`company_id`),
  CONSTRAINT `FK_stocks_companies` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.stocks: ~0 rows (approximately)

-- Dumping structure for table orders.sub_center
CREATE TABLE IF NOT EXISTS `sub_center` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `id_center` int(20) NOT NULL,
  `name` char(250) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK__centers` (`id_center`),
  CONSTRAINT `FK__centers` FOREIGN KEY (`id_center`) REFERENCES `centers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=806 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.sub_center: ~797 rows (approximately)
INSERT INTO `sub_center` (`id`, `id_center`, `name`) VALUES
	(2, 9, 'ابو شنب'),
	(3, 9, 'العجميين'),
	(4, 9, 'ثلات'),
	(12, 9, ' فيديمين'),
	(13, 9, 'الفيوم ابشواي بجوار المركز الطبي الحضاري'),
	(14, 9, ' ابشواى بجوار البنك الاهلى'),
	(15, 9, ' ابشواى بجوار المطافي'),
	(16, 9, ' مركز ابشواي'),
	(17, 9, 'المحافظه الفيوم\n  قرية جبر - أبشواي'),
	(18, 9, 'الفيوم ابشوى كحك بحري عند مول أ شامل'),
	(19, 9, 'محمد مصطفي ٠١٠٩٥٥٢٩١٧٧ الفيوم . يوسف الصديق. قارون. اباظه'),
	(20, 9, 'العنوان :الفيوم مركز يوسف الصديق مفارق قارون عند المسجد'),
	(21, 9, 'الفيوم +العنوان قرية كحك بحرى مركز يوسف الصديق'),
	(22, 9, 'الفيوم ابشواي قرية النصارية'),
	(23, 9, 'الفيوم مركز ابشواى قرية شرف الدين'),
	(24, 9, 'الفيوم - يوسف الصديق'),
	(25, 9, 'ابشواي مستشفي ابشواي المركزي'),
	(26, 9, 'الفيوم مركز ابشواي امام البنك الاهلي'),
	(27, 9, 'الفيوم مركز يوسف الصديق. قارون الخلطة'),
	(28, 9, 'العنوان الفيوم مركز يوسف الصديق الصبيحي'),
	(29, 9, 'الفيوم &#x2F; مركز سنورس عين السليين'),
	(30, 9, 'سنهور القبليه امام البنك الاهلي'),
	(31, 9, 'الفيوم ابشواى قرية ابودنقاش'),
	(32, 9, 'الفيوم مركز ابشواى قرية قصر الجبالى'),
	(33, 9, 'الفيوم/يوسف الصديق/مفارق قارون'),
	(34, 9, 'مركز سنورس\n قرية فيديمين\n مكتب بريد فيديمين'),
	(35, 9, 'الفيوم سنهودر بجوار مسجد الطواحين'),
	(36, 9, 'يوسف الصديق الثلثمائه'),
	(37, 9, 'الفيوم ابشواي شكشوك فوق مطعم ارزاق'),
	(38, 9, 'الفيوم مركز يوسف الصديق قريه تونس بجوار فندق ظلال'),
	(39, 9, 'سنهور ضروري'),
	(40, 9, 'الفيوم . مركز أبشواي . قريه شكشوك .أمام المدرسه الاعداديه'),
	(41, 9, 'العنوان: الفيوم مركز ابشواي شارع المحطه امام حديقه الطفل اعلى مطعم الهواري منزل يوسف منتصر'),
	(42, 9, 'العنوان محافظة الفيوم قرية تلات بجوار مسجد الرحمه رقم الموب ٠١٠٠٢١٢١٣٧٠ 01002121370'),
	(43, 9, 'الفيوم سنرو القبليه شارع المقابر محل صغير ابو كريم'),
	(44, 9, 'الفيوم سنهور القبليه بجوار مركز سنهور'),
	(45, 9, 'الفيوم الشواشنه امام مدرسه ثانوي'),
	(46, 9, 'العنوان الفيوم مركز سنورس سنهور القبليه\n بجوار المفارق'),
	(47, 9, 'ابشواي بجوار مسجد الشيخ عبدالعليم'),
	(48, 9, 'مكتب بيت الخبره امام البنك الاهلي ابشواي الفيوم - العميل هيستلم ف المكتب نفسه ولو العميل مردش يسلمه للمكتب مباشرة'),
	(49, 9, 'ابشواي شكشوك'),
	(50, 9, 'بني صالح فيلا الحج ايوب بجوار مسجد الحرمين'),
	(51, 9, 'ابشواي شركه تنميه للمشروعات'),
	(52, 9, 'طبهار بجوار مسجد العمده'),
	(53, 9, 'فيديميين مركز الشباب امام صيدليه د حماده روبي'),
	(54, 9, 'ابشواي بجوار مسجد عزام'),
	(55, 9, 'مفارق يوسف الصديق محل مهندس حسن العبادي امام المسجد'),
	(56, 9, 'ابشواي'),
	(57, 9, 'ابشواي شارع الواغط'),
	(58, 9, 'االفيوم الاداره الزراعيه بابشواى امام مكتب بريد بشواى لحد السااعه 2 ظهرا'),
	(59, 9, 'الفيوم - مركز ابشاوي قريه زيد قبال صيدليه د محمود'),
	(60, 9, 'الفيوم ابشواى مركز يوسف الصديق الخلطه'),
	(61, 9, 'الفيوم موكز ابشواي'),
	(62, 9, 'الفيوم ابشواي ابوجنشو اول طريق الصفرايه العماره6 ادوار امام الملعبالرقم01065261919'),
	(63, 9, 'الفيوم مركز ابشواى قرية النزله البيت اللى قدام قهوة الفرنساوى'),
	(64, 9, 'ابشواي ابوجنشو المنطقه الصناعيه عند مطعم بيت العيله'),
	(65, 9, 'الفيوم مركز ابشواي قرية الشهيد احمد رمضان - 01067080979'),
	(66, 9, 'الفيوم ...مركز ابشواي.... محل دلع في دلع إدارة ابو عمر....أمام اوكازيون ....اول شارع البورة في ابشواي'),
	(67, 9, 'الفيوم مراكز ابشواى قريت ابوكساه السبيل دردير الاستلام قيل الجمعة ضروري'),
	(68, 9, 'الفيوم ابشواي شكشوك أمام صيدليه محمد ربيع'),
	(69, 9, 'الفيوم مركز ابشواي بجوار مستشفي مكه'),
	(70, 9, 'الفيوم ابشواي ابو جنشوا المنطقه الصناعيه بجوار مطعم بيت العيله'),
	(71, 9, 'قرية المشرك قبلي مركز يوسف الصديق الفيوم ( بجوار مطبعة الصايم ومخبز العيش البلدي ) منزل الأستاذ عثمان علي علي'),
	(72, 9, 'الفيوم مركز ابشواي ابو كاه قرية بلونه بجوار المدرسة'),
	(73, 9, 'الفيوم مركز الشواشنه بجوار مركز الشرطه'),
	(74, 9, 'الفيوم مركز يوسف الصديق الرواشديه'),
	(75, 9, 'الفيوم &#x2F;ابشواي &#x2F; طبهار بجوار الوحده المحليه'),
	(76, 9, 'الفيوم مركز سنورس قرية سنهور القبلية'),
	(77, 9, 'الفيوم قارون قوتة'),
	(78, 9, 'يوسف الصديق الخريجين ف العماير ال ف اول البلد'),
	(79, 9, 'الفيوم سنورس سنهور القبليه الطواحين'),
	(80, 9, 'قريه الريان مركز يوسف الصديق محافظه الفيوم'),
	(81, 9, 'محافظة الفيوم مركز ابشواى ابو جنشر بجوار مدرسه التجاره'),
	(82, 9, 'قريه سنهور البحريه'),
	(83, 9, 'الفيوم ابشواى ويكلمنى على الرقم انا اكمل معاه اوك'),
	(84, 9, 'الشواشنه مشرك قبلي'),
	(85, 9, 'الفيوم فيدمين بجوار جامع محمد مرسي'),
	(86, 9, 'من الفيوم من مركز يوسف الصديق'),
	(87, 9, 'المندره طريقة ابشوى السياحي'),
	(88, 9, 'الفيوم /ابشواي /الشواشنة أمام سوبر ماركت أسواق الغمراوي.'),
	(89, 9, 'ش محمد حسين ابشواي'),
	(90, 9, 'الفيوم ابشواى العجميين'),
	(91, 9, 'ابشواي بجوار المستشفى العام'),
	(92, 9, 'الفيوم _ المشرك قبلي _ مركز يوسف الصديق'),
	(93, 9, 'الفيوم ابشواى بجوار المطحن'),
	(94, 9, 'مركز ابشواي شركو الكهرباء بجوار بنك مصر'),
	(95, 9, 'القيوم مركز ابشاوى عند المطافى'),
	(96, 9, 'الفيوم مركز ابشواي يوسف الصديق قرية حنا حبيب'),
	(97, 9, 'Address0, العنوان الفيوم كحك بحرى جامع محمد يوسف, Floor 0, Apt 0, Fayoum, Fayoum'),
	(98, 9, 'الفيوم السواسله'),
	(99, 9, 'البشواي الشواشنه بجوار اسواق الغمراوي'),
	(100, 9, 'بحيره قارون ش المركز عماره 12 شقه 6 خلف الشهر العقاري'),
	(101, 9, 'الفيوم مركز يوسف الصديق - قارون - خرابة الشيمي - بعد مفارق قارون'),
	(102, 9, 'الفيوم ابشواي النصاريه طريق الوسطاني'),
	(103, 9, 'العنوان/الفيوم -ابشواى-النزله -بجوار صيدلية خديجة'),
	(104, 9, 'الفيوم ابشواى عند موقف كحك بحرى'),
	(105, 9, 'مركز ابشواي امام البنك الاهلي'),
	(106, 9, 'الفيوم - مركز سنورس - قرية فيديمن - موقف المنجايه او موقف علي عامر'),
	(107, 9, 'الفيوم ابشواي\n 01287263271'),
	(108, 9, 'الفيوم - ابشواى - كوبرى ابو حنشو امام محل وليد عزام للاقمشة - عمارة د/انور'),
	(109, 9, 'حنا حبيب ابشواي الفيوم'),
	(110, 9, 'الفيوم - شارع النجارين'),
	(111, 9, 'العنوان الفيوم تلات منشأة سكران'),
	(112, 9, 'العنوان/ الفيوم.. ابشواي.. المدرسه الابتدائيه.. الشنطوري'),
	(113, 9, 'الفيوم ابشواي بجوار المطافي'),
	(114, 9, 'الفيوم ابشواي ش الجمهوريه'),
	(115, 9, 'الفيوم ابشواي الحامولي'),
	(116, 9, 'المندره طريق ابشواي السياحي'),
	(117, 9, 'مركز يوسف الصديق. الحامول قرية حمزاوي..بجوار قنطرة يوسف..منزل استاذ محمد جعفر جوده.'),
	(118, 9, 'فيدميين'),
	(119, 9, 'ابشواي الفيوم'),
	(120, 9, 'الفيوم ابشواى ابوجنشو كشرى راشد'),
	(121, 9, 'الفيوم مركز ابشواي ميدان المطافي محل الملكة للحلويات'),
	(122, 9, 'الفيوم &#x2F;مركز ابشواي&#x2F; قرية النزلة &#x2F; منطقة السوق القديم'),
	(123, 9, 'الفيوم_ فيديمين _موقف علي عامر'),
	(124, 9, 'الفيوم جمب مسجد الحرميين بعد المعهد الديني بني صالح'),
	(125, 9, 'الفيوم ابشواي بجوار المرور'),
	(126, 9, 'الفيوم اشبواي بجوار المستشفي العام'),
	(127, 9, 'ابشواي بجوار فرع فودافون'),
	(128, 9, 'ابشويابوكساه'),
	(129, 9, 'الفيوم يوسف الصديق قارون اباظه'),
	(130, 9, 'محافظة الفيوم مركز ابشواى ابوكساه شارع السبيل جامع المرجاوى'),
	(131, 9, 'ابو شانوي'),
	(132, 9, 'ابشواي عند المطافي'),
	(133, 9, 'الفيوم ... قريه المندره'),
	(134, 9, 'الفيوم ابشواي كفر عبود'),
	(135, 9, 'سنهور امام الجنيسه القديمه ضروري وممككن التواصل واتساب'),
	(136, 9, 'ابشواي بجوار فرع فوادفون'),
	(137, 9, 'الفيوم -مركز ابشواي -قريه هويدي - الشارع العمومي-بجوار المسجد'),
	(138, 9, 'الفيوم مركز ابشواي بلد الشواشنة عند اسواق الغراوي'),
	(139, 9, 'الفيوم مركز ابشواى امام مجلس المدينة'),
	(140, 9, 'ابشواى ابوكساه الفاروقه امام مسجد المحطه معرض اليسر السيراميك(التسليم ضرورى جدا)'),
	(141, 9, 'قرية الثلثمائة يوسف الصديق الفيوم'),
	(142, 9, 'الفيوم مركز يوسف الصديق قرية العواشنة'),
	(143, 9, 'الفيوم ابشواي ميدان المحطه خلف بنك مصر داخل شركه فايد للسياحه'),
	(144, 9, 'مركز أبشواي قريه النزله بجوار مدرسه الروضه المشتركه منزل أستاذ على صابر'),
	(145, 9, 'ش. سعد زغلول ابشواى الفيوم'),
	(146, 9, 'مركز يوسف الصديق\n المشرك قبلي\n شارع البحر عيادة الأسنان دكتور محمود عبدالعزيز'),
	(147, 9, 'مركز ابشواي المطافئ'),
	(148, 9, 'ابو كساه'),
	(149, 9, 'قرية سنرو القبليه مركز ابشواي عند فيلا الشيخ علي ابراهيم'),
	(150, 9, 'يوسف الصديق ابشواي'),
	(151, 9, 'الفيوم / ابشواى/ ابو كساه'),
	(152, 9, 'الفيوم فيدمين الطريق السياحي بعد موقف المانجايه امام جامع محمد مرسي'),
	(153, 9, 'العنوان: الفيوم ابشواي ابوجنشو اول طريق الصفرايه العماره6ادوار امام الملعب'),
	(154, 9, 'الفيوم سنورس سنهور القبليه بجوار صيدلية د أشرف الليموني'),
	(155, 9, 'الفيوم مركز ابشواي شارع المستشفى العام'),
	(156, 9, 'فيوم مركز ابشواي قريه عجمين'),
	(157, 9, 'الفيوم مركز سنورس سنهور الفيوم'),
	(158, 9, 'قريه تونس السياحه -مركز يوسف الصديق- محافظة الفيوم'),
	(159, 9, 'ابشواي ابوكساه امام الكنيسه'),
	(160, 9, 'ابو دنقاش مركز اشواي'),
	(161, 9, 'العنوان محافظه الفيوم القريه بنى صالح خلف مسجد الحرمين ببنى صالح'),
	(162, 9, 'ابشواي شارع الجيلاني بجانب صيدلية د ابراهيم'),
	(163, 9, 'بجوار البنك الاهلي'),
	(164, 9, 'قصر قارون بجانب مدرسه'),
	(165, 9, 'ابوكساه'),
	(166, 9, 'الخواجات'),
	(167, 9, 'فيديمين السجل المدني'),
	(168, 9, 'فدمين مركز الشباب'),
	(169, 9, 'بجوار مشروع المياه القديم'),
	(170, 9, 'الشواشنه'),
	(171, 9, 'خلف مسجد الاخوه'),
	(172, 9, 'سنهور القبليه محل دهب المدينه المنوره امام مسجد بدر'),
	(173, 9, 'محافظه الفيوم ابشواي ابو جنشو شارع التحرير'),
	(174, 9, 'مركز البتواي ش البحر الجديد'),
	(175, 9, 'ابشواي فرية النصاريه الفيوم'),
	(176, 9, 'الفيوم ابشواي المنشيه'),
	(177, 9, 'الفيوم &#x2F; سنهور وسط البلد'),
	(178, 9, 'الفيوم مركز الفيوم قرية بني صالح'),
	(179, 9, 'العنوان الفيوم ابشواي قصر الجبالي'),
	(180, 9, 'الفيوم سنورس فيدميين بجوار موقف على عامر'),
	(181, 9, 'الفيوم مركز ابشواي قريه العجمين بجوار مسجد الهدايه'),
	(182, 9, 'الفيوم مركز ابشواي قصر الجبالي امام البريد'),
	(183, 9, 'الفيوم مركز سنهور قريه الطوحين اول البلد'),
	(184, 9, 'ابوالحارث احمد شعبان العنوان عزبة بطرس مركز سنهور القبليه محافظة الفيوم'),
	(185, 9, 'الفيوم طريق تلات العجميين نزلت الحريشي'),
	(186, 9, 'مركز ابشواي علي البركه'),
	(187, 9, 'الفيوم مركز سنهور \n \n FAYOUM FYM \n EGYPT'),
	(188, 9, 'العجميين'),
	(189, 9, 'العنوان الفيوم /السليين/عزبه الحلفايا'),
	(190, 9, 'محافظه الفيوم مركز يوسف الصديق الشواشنة اول طريق بطن هريت بجوار المستوصف الطبي صيدلية د هبة عبد المجيد'),
	(191, 9, 'عزبة معوض بعد بحيرة قارون قبل سنهور'),
	(192, 9, 'الفيوم مركز ابشوامى قريه ابو كساه ميدان السبيل'),
	(193, 9, 'السليين'),
	(194, 9, 'يوسف الصديق شعلان صيد ليه محمد عيد الونييس'),
	(195, 9, 'العنوان محافظه الفيوم قريه سنهور القبليه الكبري بجوار مسجد بدر'),
	(196, 9, 'الفيوم مركز ابشواي قرية ابو كساة'),
	(197, 9, 'ميدان سنهور عند مسجد الطواحين'),
	(198, 9, 'المشرك قبلي يوسف الصديق'),
	(199, 9, 'الفيوم / ابشواي /مركز يوسف الصديق / قارون / قوته'),
	(200, 9, 'الفيوم مركز ابشوي'),
	(201, 9, 'الفيوم سنورس بحيره قارون قاعه اللؤلؤه قريه محمد يوسف'),
	(202, 9, 'الفيوم مركز ابشواى قرية طبهار'),
	(203, 9, 'فيوم مركز اشنونن قريهخ بعد مدرسه همر الخولي الابتدائيه .'),
	(204, 9, 'الفيوم مركز ابشواي قرية طبهار او الفيوم موقف مصر بجوار بنزينة التعاون'),
	(205, 9, 'الفيوم ابشواي شارع الجمهوريه بجوار كازيون\n FYM\n FAYOUM\n EGYPT'),
	(206, 9, 'الشواشته ابشواى'),
	(207, 9, 'الشواشنه او شكشوك'),
	(208, 9, 'الفيوم ابشواي'),
	(209, 9, 'الحامولي'),
	(210, 9, 'قريه الصعايده'),
	(211, 9, 'ابشواي النزله بجوار صيدليه د.خديجه'),
	(212, 9, 'الفيوم ابشواى شعلان'),
	(213, 9, 'الفيوم سنسورس موقف سنهور القبليه قصاد كشري اللؤلؤة'),
	(214, 9, 'الفيوم بحيرة قارون بجانب نادي الشباب في شكشوك'),
	(215, 9, 'الفيوم مركز ا بشواي عند النازله'),
	(216, 9, 'تلات تبع الفيوم'),
	(217, 9, 'الفيوم مركز يوسف الصديق امام مول عصام عبد الله'),
	(218, 9, 'فيديمين عند موقف الحاج عامر هبعت حد ياخده مش هيدخل جوا البلد او لو عرفت اوفق مع المندوب اخده منه من الفيوم نفسها'),
	(219, 9, 'الفيوم طبهار عند موقف الشوارع'),
	(220, 9, 'الفيوم مركز ابشواي قريت العجميين بجوار منزل يوسف الشازلي'),
	(221, 9, 'العنوان الفيوم مركز ابشواي مفارق يوسف الصديق'),
	(222, 9, 'الفيوم ابشواى بجوار المعهد الدينى'),
	(223, 9, 'الفيوم ابشواي شارع الساقيه'),
	(224, 9, 'الفيوم اشواق ابودنقاس'),
	(225, 9, 'الفيوم مركز ابشواي قرية أبو شنب الفيوم'),
	(226, 9, 'من قريت بني صالح'),
	(227, 9, 'محافظة الفيوم مركز ابشواي شارع الساقيه مقابل المعهد الازهري'),
	(228, 9, 'ساميه عبد العزيز محمد محافظه الفيوم مركز ابشواى قريه طبهار درب الوابور'),
	(229, 9, 'العنوان :الفيوم -ابشواي بجوار البنك الاهلي'),
	(230, 9, 'رائد صلاح الفيوم يوسف الصديق مشرك قبلى 01068297976'),
	(231, 9, 'الفيوم مركز الفيوم زاوية الكرادسة'),
	(232, 9, 'الفيوم مركز ابيشواي بلونه'),
	(233, 9, 'الفيوم / مركز ابشواي/ كوبري ابشواي أمام محل خضروات وفواكه حسين أبو عرب'),
	(234, 9, 'العنوان الفيوم /ابشواي /النزله'),
	(235, 9, 'الفيوم ابشواي'),
	(236, 9, 'الفيوم ابشواي - ابوكساه الفاروقة بجوار المدرسة الإبتدائية المشتركة منزل حمدي محمود'),
	(237, 9, 'الفيوم السيليين عند المراجيح'),
	(238, 9, 'الفيوم ابشواي ابو شنب'),
	(239, 9, 'قوته قارون يوسف الصديق'),
	(240, 9, 'الفيوم مركز سنهور يمين موقف على عامر عماره على زهران'),
	(241, 9, 'ركز ابشواي قرية ايوكساه ميدان السبيل'),
	(242, 9, 'قرية تلات'),
	(243, 9, 'ميدان سنهور معرض الشريف'),
	(244, 9, 'الفيوم ايشواي بجوار معمل البرج'),
	(245, 9, 'مركز الستورس قرية فيديمين بجوار موقف علي عامر'),
	(246, 9, 'الفيوم ابشوايي امام المدرسه الثاويه'),
	(247, 9, 'ابشواي نزله'),
	(248, 9, 'الفيوم ابشواي ابوكساه عن كوبري معبد'),
	(249, 9, 'محافظة الفيوم ابشواي قصر الجبالي عند البنزينه'),
	(250, 9, 'الفيوم مركز ابشواي بجوار ماستر للكمبيوتر'),
	(251, 9, 'م الفيوم م ابشواي بجوار مركز ابشواي'),
	(252, 9, 'بحير قارون'),
	(253, 9, 'الفيوم ابشواي المشرك عفيفي'),
	(254, 9, 'الفيوم بدروسين الشرقيه يوسف الصديق المشرك البحري'),
	(255, 9, 'ابشواي الفيوم امام المطافي'),
	(256, 9, 'الفيوم مركز يوسف الصديق مفارق يوسف الصديق بجوار بنزينه التعاون'),
	(257, 9, 'الفيوم - يوسف الصديق - مفارق قارون'),
	(258, 9, 'خلف البنك الاهلي ابشواي'),
	(259, 9, 'الفيوم /مركز سنورس/ قريه فيديمين'),
	(260, 9, 'الفيوم ابشواي بجوار مدرسه الثانويه العامه للبنات محل عصير العابد'),
	(261, 9, 'الفيوم. يوسف الصديق. الحامولى'),
	(262, 9, 'الفيوم مركز الفيوم زاوية الكرادسه اول البلد امام ارض الاوقاف'),
	(263, 9, 'كحك بحري بحيره قارون'),
	(264, 9, 'ابشواي مفارق يوسف الصديق'),
	(265, 9, 'الفيوم \n مركز يوسف الصديق قرية النزله عند موقف العربيات بجوار فرع اتصالات'),
	(266, 9, 'الفيوم ابشواي عند المطافي'),
	(267, 9, 'الفيوم ابشواي قريه ابوكساه'),
	(268, 9, 'المنشيه البحريه'),
	(269, 9, 'سنهور عزبه محمد يوسف'),
	(270, 9, 'الفيوم جنب فندق القوات المسلحه ع بحيره قارون'),
	(271, 9, 'يوسف الصديق تونس'),
	(272, 9, 'يوسف الصديق قارون'),
	(273, 9, 'محافظه الفيوم مركز يوسف الصديق قريه الرواشدية بجوار سوبر ماركت المحمديه'),
	(274, 9, 'الفيوم /ابشواي/قصر الجبالي'),
	(275, 9, 'الفيوم سنهور القبليه'),
	(276, 9, 'الفيوم فيدمين'),
	(277, 9, 'الفيوم ابشواي بجوار موقف كحك الفيوم'),
	(278, 9, 'الفيوم مركز بني صاالح'),
	(279, 9, 'الفيوم سنهور القبلية بجوار فرن عبدالله دياب'),
	(280, 9, 'الفيوم ابشواي شكشوك'),
	(281, 9, 'الفيوم مركز ابشواي عند فندق القوات المسلحه'),
	(282, 9, 'الفيوم ابشواي قرية سنرو القبلية عند المعهد الديني القديم التواصل علي الرقم الاراضي'),
	(283, 9, 'الفيوم ابو كساه ابشواي'),
	(284, 9, 'الفيوم , الفيوم , محافظة الفيوم - الابعديه مركز يوسف الصديق قرية الابعدية منزل الاستاذ عادل طاهر ميزار'),
	(285, 9, 'قارون مركز يوسف الصديق'),
	(286, 9, 'المشرك'),
	(287, 9, 'طبهار ضروري جداا من بعد الساعه4'),
	(288, 9, 'بني صالح عند المظله'),
	(289, 9, 'ابشواي ابو جنشو شارع الروبي بيت احمد مصطفي'),
	(290, 9, 'ش البوره شارع سعد زغلول'),
	(291, 9, 'المكان الفيوم ابشواي النزله الصوق القديم بجوار جامع الرحمه'),
	(292, 9, 'الفيوم مركز ابشواي'),
	(293, 9, 'الفيوم ، سنرو ، عزبة دكم ، فيلا العمدة محمد دكم'),
	(294, 9, ' مركز ابشواي قرية ابوكساه كوبري معبد او مسجد معبد'),
	(295, 9, 'بجوار المطافي'),
	(296, 9, 'العنوان الفيوم سنهور القبليه بجوار مركز سنهور'),
	(297, 9, 'مدينة الشواشنة بجوار مستشفي الشواشنة'),
	(298, 9, 'ع. محافظه الفيوم مركز يوسف الصديق قرية الصعايده أمام مسجد السيده خديجه'),
	(299, 9, 'السنباط'),
	(300, 9, 'مركز يوسف الصديق\n  المشرك قبلي بجوار سنترال الاصدقاء طريق زكي صالح'),
	(301, 9, 'الفيوم مركز ابشواي قريه ابوكساه'),
	(302, 9, 'الفيوم ابشواي ابوجنشو مسجد الشيخ منصور منزل بهاء الدين المحامي'),
	(303, 9, 'ابشواي زيد'),
	(304, 9, 'العجميين بجور المدرسه الفنيه'),
	(305, 9, 'المسله بجوار البنزينه تحويل ابشواي'),
	(306, 9, 'الفيوم-سنهور-عندالكنيسه'),
	(307, 9, 'الفيوم. ابشواي. قرية الخواجات. علي الكوبري'),
	(308, 9, 'الفيوم سنهور القبليه محل مصوغات ومجوهرات المدينه المنوره امام مسجد بدر'),
	(309, 9, 'الفيوم  سنورس السليين'),
	(310, 9, 'الفيوم سنهور القبلية عزبة عبدالله عليوة طريق بحيرة قارون'),
	(311, 9, 'العنوان الفيوم سنهور الاقليه مسجد غلاب'),
	(312, 9, 'الفيوم ابشواي عند مستشفى العام بتاعت ابشواي'),
	(313, 9, 'الفيوم يوسف الصديق الشواشنه'),
	(314, 9, 'الفيوم مركز أبشواى'),
	(315, 9, 'سنهور القبليه وليده'),
	(316, 9, 'الفيوم ابشواي النزله المقراني منزل جمال كمال الدين شارع ١١'),
	(317, 9, 'ندا اسماعيل محافظه الفيوم مركز ابشواي امام المطافي'),
	(318, 9, 'شكشوك'),
	(319, 9, 'الفيوم مفارق يوسف الصديق محل النهندس حسن حوده امام مسجد'),
	(320, 9, 'قرية الحريشي طريق تلات'),
	(321, 9, 'الفيوم مركز يوسف الصديق'),
	(322, 9, 'مركز إبشواي قريه العجمين عند مجلس المحلي مسجد محمد عبد المجيد إبشواي'),
	(323, 9, 'الفيوم مركز يوسف الصديق قريه الشواشينه'),
	(324, 9, 'الفيوم مركز يوسف الصديق طريق بحيره قرون قريه الشرفدي'),
	(325, 9, 'ابو دنقاش'),
	(326, 9, 'الفيوم مركز ابشواي سنرو القبلية فيلا محسن الجمل'),
	(327, 9, 'الفيوم مركز ابشواي شرق السكه الحديد'),
	(328, 9, 'الفيوم - أبشواي - قرية النزلة'),
	(329, 9, 'الفيوم مركز ابشواي سنرو القبليه شارع المدارس بجوار المسجد البحري'),
	(330, 9, 'قرية تلات بجوار الجامع الوسطاني اعلي محل ابو حمدي تلات مركز الفيوم'),
	(331, 9, 'مركز سنهور القبلية امام مسجد فودة الفيوم'),
	(332, 9, 'ابشواي ابو جنشو بجوار د / عباس عند مدرسه التجاره'),
	(333, 9, 'مركز ابشواي قرية العجميين بجوار المعهد الدييني مركز ابشواي الفيوم'),
	(334, 9, 'الفيوم - العمدية بالنصارية مركز ابشواي'),
	(335, 9, 'الفيوم ابشواي قريه النزله منزل محمود علي السيد الموقف'),
	(336, 9, 'العنوان- الفيوم،ابشواي،مركز يوسف الصديق قرية كحك بحري بجوار مول المصري'),
	(337, 9, 'الفيوم-سنهور القبلية-المفارق-شارع المغربي بجوار الاسعاف'),
	(338, 9, 'الفيوم مركز اشوي بجوار موقف الخالدية'),
	(339, 9, 'الفيوم - المندره الكوبري الجديد - بجوار مدرسه المندره الابتدائيه'),
	(340, 9, 'الفيوم السيليين الطريق السياحي امام مسجد'),
	(341, 9, 'الفيوم مركز يوسف الصديق قريه تونس'),
	(342, 9, 'قريه سنرو القبلية على طريق ابشواى السياحى محافظه الفيوم'),
	(343, 9, 'محافظة الفيوم مركز ابشواى قريه شكشوك'),
	(344, 9, 'الفيوم مركز ابشواي قرية ابوكساه 01091495909'),
	(345, 9, 'الفيوم ابشواي عند بنك القاهره الكوبري'),
	(346, 9, 'زاوية الكرداسه مغلسه اكس بريس'),
	(347, 9, 'الفيوم مركز يوسف الصديق - قرية الصبيحي - بجوار نادي الصفوة'),
	(348, 9, 'الفيوم ابشواى النزله'),
	(349, 9, 'منزل سيد ربيع احمد عبدالشافي امام المساكن السليين'),
	(350, 9, 'الفيوم مركز يوسف الصديق بجوار مكتب البريد'),
	(351, 9, 'الفيوم منشأة فتيح بجوار مدرسه الاورمان مدخل العجميين'),
	(352, 9, 'الفيوم الطريق السياحى مرفق المانجه فيدميين'),
	(353, 9, 'الفيوم ابشواي طبهار'),
	(354, 9, 'الفيوم يوسف الصديق'),
	(355, 9, 'الفيوم مركز يوسف الصديق القرية التانية'),
	(356, 9, 'الفيوم سنهور علام'),
	(357, 9, 'الفيوم يوسف الصديق'),
	(358, 9, 'الفيوم يوسف الصديق'),
	(359, 9, 'الفيوم - قديمين موقف علي عامر'),
	(360, 9, 'الفيوم مركز ابشواي قريه ابوكسه'),
	(361, 9, 'الفيوم يوسف الصديق بريش الغربي'),
	(362, 9, 'العنوان الفيوم ابشواى امام كازيون'),
	(363, 9, 'الفيوم زاويه الكرداسه'),
	(364, 9, 'الفيوم سنهور'),
	(365, 9, 'للعنوان قصر بياض ٠'),
	(366, 9, 'الفيوم - سنورس - فيديمين'),
	(367, 9, 'ابشواي قرية الروشدية'),
	(368, 9, 'قرية تونس'),
	(369, 9, 'الفيوم يوسف الصديق بريش الغربي'),
	(370, 9, 'مركز الفيوم قرية بني صالح بجوار البريد'),
	(371, 9, 'فيدميين المثلث'),
	(372, 9, 'الفيوم سالم جاد المشرك قبلى يوسف الصديق'),
	(373, 9, 'الفيوم مركز يوسف الصديق قصر الجبالي'),
	(374, 9, 'الفيوم مركز (ابي شواى) قريه طبهار بجوار مفارق طبهار وجردو و المناشى منزل الماذون صلاح عبد الستار'),
	(375, 9, 'الفيوم - مركز ابشواي قرية كحك بحري بجوار مسجد محمد يوسف إبشواي'),
	(376, 9, 'العجميين مركز ابشواي بجوار وحدة العلمين إبشواي'),
	(377, 9, 'الفيوم ابشواي الشواشنه بجوار المدرسه الثانويه'),
	(378, 9, 'كفر عبود المدرسه الاعداديه'),
	(379, 9, 'فيدمين'),
	(380, 9, 'كحك بحري مسجد عباس'),
	(381, 9, 'الفيوم..مركز سنهور فيديمين ..موقف علي عامر عمارة علي زهران'),
	(382, 9, 'ابو صايم مطعم ولاد البلد'),
	(383, 9, 'سنهور الطواحين'),
	(384, 9, 'ابو كساة'),
	(385, 9, 'الفيوم..مركز سنهور فيديمين ..موقف علي عامر عمارة علي زهران'),
	(386, 9, 'يوسف الصديق قريه الخرابه الشيمي'),
	(387, 9, 'القريه الاولي'),
	(388, 9, 'بحيره قارون  قبل فندق القوات المسلحه'),
	(389, 9, 'الفيوم مركز ابشواي شارع المطافي بجوار شركه WE'),
	(390, 9, 'بني صالح مركز الفيوم بجوار البريد المصري شارع المدرسه'),
	(391, 9, 'الفيوم ابشواي ابوكساه حزين'),
	(392, 9, 'المشرك قبلي'),
	(393, 9, 'المشرك قبلي'),
	(394, 9, 'المنشيه'),
	(395, 9, 'من خط شعلان ل الريان'),
	(396, 9, 'الفيوم المشرق قبلي'),
	(397, 9, 'الفيوم المندرة الكيمان'),
	(398, 9, 'الفيوم ابشوي واما توصل ابشواي اسأل ع ذيد ولما توصل ذيد ابقى قولي'),
	(399, 9, 'الفيوم يوسف الصديق الشواشنه'),
	(400, 9, 'الفيوم مركز ابشواى سنرو القبلية شارع المدرسة'),
	(401, 9, 'الفيوم ابشواي ابوكساه السياحي امام مو صلاح'),
	(402, 9, 'شارع الرزنه قرية الصبيحي بجوار مسجد الرزنه مركز يوسف الصديق'),
	(403, 9, 'الفيوم يوسف الصديق قارون الخلطه'),
	(404, 9, 'المنشيه'),
	(405, 9, 'ابوكساه ميدان السبيل'),
	(406, 9, 'الشواشنة كحك بحري بجوار مول المصري'),
	(407, 9, 'في مستشفى ابشواي المركزي هيستلم في ابوكساه'),
	(408, 9, 'النزله'),
	(409, 9, 'محافظه الفيوم مركز ابشواي قريه الحامولي'),
	(410, 9, 'العنوان الفيوم مركز يوسف الصديق شارع احمد افندي'),
	(411, 9, 'العنوان الفيوم. مركز ابشواي قرية كحك بحري'),
	(412, 9, 'النزله'),
	(413, 9, 'مركز ابشواي قريه ابودنقاش'),
	(414, 9, 'الفيوم ابشواي سنرو'),
	(415, 9, 'النزله'),
	(416, 9, 'النصاريه'),
	(417, 9, 'الفيوم \n مركز سنورس قريه سنهور البحريه امام اللمدرسه الابتدأيه**عبوه'),
	(418, 9, 'المندرة / الكوبري القديم / محافظة الفيوم'),
	(419, 9, 'قرية أبو شنب بجوار الوحدة المحلية'),
	(420, 9, 'الفيوم مركز يوسف الصديق قرية بطن اهريت'),
	(421, 9, 'Address: الفيوم- ابشواي - شارع المستشفى - برج شركة الغاز'),
	(422, 9, 'ابشواي قريه الريان'),
	(423, 9, 'تلات الفيوم مركز الفيوم'),
	(424, 9, 'الفيوم مركز ابشواي قريه سنرو'),
	(425, 9, 'النصاريه'),
	(426, 9, 'الفيوم.ابشواي.النصاريه بجوار مدرسه عمر الخولي'),
	(427, 9, 'مركز يوسف الصديق قرية الريان'),
	(428, 9, 'تونس'),
	(429, 9, 'فديمين موقف على عامر الفيوم'),
	(430, 9, 'مركز ابشواي شارع الجمهوريه بجوار مسجد الحضانه'),
	(431, 9, 'ابشواي شارع البوره بجوار مسجد عاشور إبشواي'),
	(432, 9, 'ابو صايم'),
	(433, 9, 'النصاريه'),
	(434, 9, 'إبشواي'),
	(435, 9, 'سنهور القبليه عند المفارق عند مسجد الكويتي بالظبط'),
	(436, 9, 'يوسف الصديق قريه ابو لطيعه'),
	(437, 9, 'سنهور البحريه'),
	(438, 9, 'إبشواي'),
	(439, 9, 'الفيوم قريه العجميين'),
	(440, 9, 'مركز يوسف الصديق المشرك قبلي الصببحي ع الكوبري'),
	(441, 9, 'الفيوم مركز ابشواي قريه النصاريه بجوار مسجد النورق'),
	(442, 9, 'لفيوم مركز يوسف الصديق حناحببب بجوار صيدليه الدكتور اسماعيل الشيمي'),
	(443, 9, 'إبشواي'),
	(444, 9, 'الفيوم بجوار مسجد الجمعيه الخيريه ابشواي'),
	(445, 9, 'ابوشنب مركز ابشواي'),
	(446, 9, 'مركز ابشواي قرية ابوكساه'),
	(447, 9, '،الفيوم مركز الشواشنه ،0'),
	(448, 9, 'إبشواي'),
	(449, 9, 'الفيوم مركز سنورس سيلين امام المسجد الكبير'),
	(450, 9, 'العنوان الفيوم سنهور القبلية'),
	(451, 9, 'الفيوم - سنرو القبلية - امام البريد'),
	(452, 9, 'الفيوم الشواشنه الرواشدية أول القريه من جة الشرق \n طريق ابشواى كحك قبلي الرواشدية'),
	(453, 9, 'ابشواي مستشفي مكه'),
	(454, 9, 'إبشواي'),
	(455, 9, 'إبشواي'),
	(456, 9, 'إبشواي'),
	(457, 9, 'إبشواي'),
	(458, 9, 'إبشواي'),
	(459, 9, 'إبشواي'),
	(460, 9, 'طبهار بجوار قهوه الدهشان'),
	(461, 9, 'إبشواي'),
	(462, 9, 'بني صالح'),
	(463, 9, 'بني صالح'),
	(464, 9, 'الفيوم مركز يوسف الصديق - قارون -القرية الثانية - بجوار المسجد الكبير -أمام صيدلية د /مسعود'),
	(465, 9, 'الفيوم مركز سنيورس قريه سيد مني سوبر ماركت ابو شادى بجوار موقف على عامر'),
	(466, 9, 'الفيوم قرية طبهار'),
	(467, 9, 'غير مسموح بالفتح \n الفيوم مركز ابشواي بجوار ماستر للكمبيوتر'),
	(468, 9, 'بني صالح'),
	(469, 9, 'في الحمولي الفيوم'),
	(470, 9, 'بني صالح شارع السبعه'),
	(471, 9, 'سنرو القبليه'),
	(472, 9, 'محافظة الفيوم مركز ابشواي مقيم في المالحه'),
	(473, 9, 'سنرو القبليه'),
	(474, 9, 'عند مفارق قارون'),
	(475, 9, 'سنهور'),
	(476, 9, 'الفيوم سنهور'),
	(477, 9, 'سنهور'),
	(478, 9, 'سنهور'),
	(479, 9, 'الفيوم\n أبشواي شارع المستشفي العام طريق ابوكساه'),
	(480, 9, 'محافظه الفيوم مركز ابشواي امام امن الدوله'),
	(481, 9, 'سنهور'),
	(482, 9, 'ابشواي كحك بحري'),
	(483, 9, 'ابوكساه'),
	(484, 9, 'الفيوم يوسف الصديق قريه غيدان بجوار المستشفى'),
	(485, 9, 'سنهور'),
	(486, 9, 'الفيوم الدائري دخله المندره فيلا اشرف ميزار'),
	(487, 9, 'السلسبين ينزل عند القهوه العموميه بجوار جامع الرحمن الفيوم'),
	(488, 9, 'سنهور'),
	(489, 9, 'الفيوم/ابشواي/قصرالجبالي'),
	(490, 9, 'الفيوم ابشواي قبلي'),
	(491, 9, 'الفيوم مركذ سنورس قريه سنهور المنذل امام مسجد بدر 01050525105'),
	(492, 9, 'الفيوم مركز ابشواي بجوار البنك الاهلي'),
	(493, 9, 'الفيوم مركز سنورس سنهور القبلية ع العصر لان العميل بيبقي نايم'),
	(494, 9, 'الفيوم ابشواي ع طريق السياحي بحيرة قارون قريه الصعايدة'),
	(495, 9, 'الفيوم قريه تلات عند مسجد الفاروق عمر بن الخطاب'),
	(496, 9, 'الفيوم مركز سنورس - قرية سنهور - منطقة المجمع بجوار مدرسة ياسين عليوة الابتدائية'),
	(497, 9, 'سنهور'),
	(498, 9, 'سنهور'),
	(499, 9, 'سنهور'),
	(500, 9, 'امام مسجد الشريف في سنهور'),
	(501, 9, 'الفيوم مركز السنباط بجوار عماره المهندس امين'),
	(502, 9, 'محافظه الفيوم نزله بشير'),
	(503, 9, 'قرية زاوية كرداسة / علي طريق سنهور / بجوار مغسلة الجزيرة'),
	(504, 9, 'المكان الفيوم قريت فيدمين بجوار محلات الاازوار'),
	(505, 9, 'الفيوم مركز بشواى عزبة شرف الدين'),
	(506, 9, 'تبشواي'),
	(507, 9, 'الفيوم ابشواى شارع الجمهورية'),
	(508, 9, 'العنوان/ الفيوم مركز ابشواي ابوكساه'),
	(509, 9, 'ابشواي ابوكساه عند الكنيسه هنعطي للعميل 435'),
	(510, 9, 'ابشواي  كفر عبود'),
	(511, 9, 'سنهور'),
	(512, 9, 'سنهور'),
	(513, 9, 'يوسف الصديق الخلطه'),
	(514, 9, 'يوسف الصديق قارون القريه الاولي معرض الفخراني'),
	(515, 9, 'التوفيقيه'),
	(516, 9, 'المندره'),
	(517, 9, 'يوسف الصديق الصبيحي'),
	(518, 9, 'سنهور البحريه'),
	(519, 9, 'محافظه الفيوم مركز سنورس مدينه السيليين'),
	(520, 9, 'الفيوم ابشواي جبل التجار'),
	(521, 9, 'مركز يوسف الصديق قرية طريق السياحي'),
	(522, 9, 'الفيوم مركز يوسف الصديف ش السجل المدني'),
	(523, 9, 'الفيوم مركز ابشواي كوبري ابو جنشوا بجوار كشري الشيماء'),
	(524, 9, 'سنهور البحريه'),
	(525, 9, 'سنهور القبليه'),
	(526, 9, 'الفيوم ابشواى قرية طبهار'),
	(527, 9, 'الفيوم سنهور القبليه اول عزبه جاب الله'),
	(528, 9, 'الفيوم ابشواى قرية النزله'),
	(529, 9, 'العجمين عزبت ابو شنب الفيوم'),
	(530, 9, 'الفيوم مركز يوسف الصديق الرواشدية شارع المغسلة'),
	(531, 9, 'الطريق السياحي بعد المثلث امام ابوعزت'),
	(532, 9, 'الفيوم ابشواي امام مسجد الحضانة'),
	(533, 9, 'الفيوم مركز ابشواي طحاوي'),
	(534, 9, 'الفيوم سنهور كفتريا اللؤلؤة بحيرة قارون'),
	(535, 9, 'عزبه خضير قبل كحك السياحي مركز الشواشنه'),
	(536, 9, 'سنورس بحيره قارون قاعه اللؤلؤه'),
	(537, 9, 'مركز ابشواي شكشوك البركه خلف المدرسه الابتدائي منزل الشيخ يوسف'),
	(538, 9, 'فدمين غرب البلد فيلا الشاهد'),
	(539, 9, 'الفيوم يوسف الصديق مدرسة القرية الثالثة أنا شغال في المدرسة'),
	(540, 9, 'الفيوم مركز ابشواي قرية ابو دنقاش'),
	(541, 9, 'الفيوم مركز ابشواي الطريق السياحي بجوار كافية العمده معرض سايبس للدهانات البيت الحديث'),
	(542, 9, 'سنهور القبليه عند المفارق'),
	(543, 9, 'يوسف الصديق قريه تونس بجوار فندق ظلال النخيل'),
	(544, 9, 'الرواشديه الشواشنه'),
	(545, 9, 'ابشواي كفر عبود'),
	(546, 9, 'الفيوم مركز ابشواي قريه شكشوك'),
	(547, 9, 'محافظه الفيوم مركز سنهور فيديمن'),
	(548, 9, 'العنوان /مصر . الفيوم . ابشواى .الشواشنه .بجوار قسم شرطه الشواشنه .منزل الحاج صبرى سليمان \n رقم التلفون /'),
	(549, 9, 'الفيوم مركز سنورس قريه سنهور القبليه منزل الشيخ علي جبيلي'),
	(550, 9, 'ابشواي امام مجلس المدينه'),
	(551, 9, 'سنهور القبليه'),
	(552, 9, 'مركز ابشواى - شارع البورة - بجوار صيدلية احمد فؤاد'),
	(553, 9, 'ش شعبان بجوار مسجد العمده'),
	(554, 9, 'جبل النجار'),
	(555, 9, 'سنهور القبليه'),
	(556, 9, 'منتجع نورياس ع البحر'),
	(557, 9, 'سنهور عزبه ابو سلام'),
	(558, 9, 'سنهور القبليه عند الجمعيه الزراعيه'),
	(559, 9, 'طبهار تشوين خالد محمد فرج'),
	(560, 9, 'فيديمين موقف الحج علي عامر'),
	(561, 9, 'ابشواي المحافظه توفيق حنين'),
	(562, 9, 'سنهور القبليه'),
	(563, 9, 'سنهور القبليه'),
	(564, 9, 'سنهور القبليه'),
	(565, 9, 'ش الجلاء ابشواي'),
	(566, 9, 'سنهور القبليه'),
	(567, 9, 'مركز يوسف الصديق'),
	(568, 9, 'سنهور القبليه'),
	(569, 9, 'قريه تبهار عند موقف الفيوم امام اكشن منزل الحاج محمد عبد الرشيد'),
	(570, 9, 'سنهور القبليه'),
	(571, 9, 'فيديمين مقابل سجل مدني'),
	(572, 9, 'سنهور القبليه'),
	(573, 9, 'العجمين الشارع الجنينه'),
	(574, 9, 'سنهور القبليه'),
	(575, 9, 'مركز يوسف الصديق قارون قوته بجوار صيدليه الدكتور'),
	(576, 9, 'سنهور القبليه'),
	(577, 9, 'ابشواي عند فرع اوكازيون'),
	(578, 9, 'ابشواي جامع الاخوه او بنك القاهره'),
	(579, 9, 'يوس الصديق قريه كحك بحري مول المصري مقر عمل'),
	(580, 9, 'شارع المدارس الابتدائيه بالسنباط'),
	(581, 9, 'الفيوم مركز ابشواي شارع د.مها'),
	(582, 9, 'محافظه الفيوم - سنهور - ميدان المفارق'),
	(583, 9, 'الفيوم ابشواي ع كوبري ابو جنشو معمل ميدان بجوار بنك القاهرة'),
	(584, 9, 'البيت الفيوم مركز سنورس فيديمين'),
	(585, 9, 'الفيوم مركز الفيوم قرية تلات'),
	(586, 9, 'العنوان محافظة الفيوم قرية تلات بداخل البلد'),
	(587, 9, 'الفيوم يوسف الصديق كحك بحرى'),
	(588, 9, 'قريه قوته بجوارمسجدعبدالمجيدمصباح'),
	(589, 9, 'سنهور القبليه'),
	(590, 9, 'ميدو الفيوم مركز ابشواى قريه ابو كساه المساكن شارحع الرحمه 01024844835'),
	(591, 9, 'قريه ابو كساه'),
	(592, 9, 'مركز ابشواي قرية كحك قبلي الجامع الكبير'),
	(593, 9, 'ابشواي النزله بجوار مسجد الرحمه'),
	(594, 9, 'مركز ابشواي النزله بجوار الموقف'),
	(595, 9, 'الفيوم _ مركز يوسف الصديق _ قريه المشرك قبلي'),
	(596, 9, 'الفيوم اشواي الشواشنه بجوار البريد'),
	(597, 9, 'سنهور القبليه'),
	(598, 9, 'الفيوم مركز ابشواي العحميين'),
	(599, 9, 'محافظه الفيوم ابشواى قهوه حسن'),
	(600, 9, 'المشرك قبلي _ الفيوم _ مركز يوسف صادق'),
	(601, 9, 'الفيوم،ابشواي،ابوكساه ،بجوار مسجد معبد'),
	(602, 9, 'الفيوم ابشواي الخواجات حناحبيب'),
	(603, 9, 'ام حبيبه الفيوم مركز الصديق قارون مفارق يوسف 01032356359'),
	(604, 9, 'الفيوم بني صالح امام البريد'),
	(605, 9, 'الفيوم بني صالح طريق السليين بحيرة قارون جنب مسجد التقوي الي في بني صالح'),
	(606, 9, 'سنهور القبليه المفارق'),
	(607, 9, 'سنهور القبليه المفارق'),
	(608, 9, 'شارع سعد زغلول'),
	(609, 9, 'قريه المندره'),
	(610, 9, 'ابشواى امام المطافى'),
	(611, 9, 'ابشواي قريه شرف الدين بجوار محطه البنزين'),
	(612, 9, 'محافظه الفيوم مركز ابشواي الجيلاني على طريق مصر السياحي'),
	(613, 9, 'مركز ابشواى - شارع الجلاء - بجوار المطحن'),
	(614, 9, 'شكشوك'),
	(615, 9, 'شكشوك'),
	(616, 9, 'كفر عبود'),
	(617, 9, 'الجبلاني ابشواي الفيوم'),
	(618, 9, 'محافظه الفيوم مركز ابشواي يجوار محكمة ابشواي نزلت البوره شارع سعد زغلول عماره النقيب مصطفى عبدالحكيم'),
	(619, 9, 'محافظة الفيوم مركز يوسف الصديق قرية الحامولي'),
	(620, 9, 'الفيوم اشواي بجوار مسجد الشيخ علدالعليم'),
	(621, 9, 'الفيوم ابشواي قصر الجبالي'),
	(622, 9, 'الفيوم مركز ابشواي يوسف الصديق قريه اباظه قارون'),
	(623, 9, 'ابو شنب ابشواي الفيوم منزل الحاج احمد محمود بجوار المدرسه الابتدائيه'),
	(624, 9, 'الفيوم مركز ابشواي امام البنك الاهلي شارع الصعايده علي اول الشارع محل ابوطالب للمحمول'),
	(625, 9, 'ابشواي الجيلاني بجوار مقابر الجيلاني الفيوم'),
	(626, 9, 'الفيوم مركز سنورس قرية فيديمين'),
	(627, 9, 'محمد من الفيوم مركز يوسف الصديق مفارق قارون'),
	(628, 9, 'محافظه الفيوم مركز ابشواي قريه النزله'),
	(629, 9, 'الفيوم ابشواى كحك'),
	(630, 9, 'العنوان ـ الفيوم مركز سنهور القبلية ـ شارع السويقه بجوار مسجد'),
	(631, 9, 'مركز ابشواي قريه ابو كشاق'),
	(632, 9, 'قريه الشيخ فضل'),
	(633, 9, 'قرية أبو كساه'),
	(634, 9, 'الفيوم علي البركة ف فندق الواحة'),
	(635, 9, 'الفيوم، مركز يوسف الصديق، قارون، قوتة'),
	(636, 9, 'شكشوك'),
	(637, 9, 'الفيوم ابشواي ماهو متسجل في العنوان لمحل شيخ العطارين 2 قدام البنك الاهلي'),
	(638, 9, 'مركز ابشواي كحك بحري'),
	(639, 9, 'الفيوم اشواي الصبيحي'),
	(640, 9, 'محافظه الفيوم بني صالح'),
	(641, 9, 'العنوان الفيوم مركز يوسف الصديق قارون الخلطه صاحب محل حدايد وبويات'),
	(642, 9, 'شكشوك'),
	(643, 9, 'يوسف الصديق قرية حنا حبيب شارع الجامعه'),
	(644, 9, 'طبهار'),
	(645, 9, 'طبهار'),
	(646, 9, 'ابشواي كفر عمرو'),
	(647, 9, 'طبهار'),
	(648, 9, 'ابشواي'),
	(649, 9, 'طبهار'),
	(650, 9, 'الفيوم مركز ابشواي قريه طبهار عند استديو فادي كلر'),
	(651, 9, 'ابو كساه شارع الفاوي'),
	(652, 9, 'طبهار'),
	(653, 9, 'الفيوم مركز الصديق قريه حنا حبيب منزل السيد محمد مهران'),
	(654, 9, 'الفيوم مركز الشواشنه المشرك قبلي سنترال الاصدقاء'),
	(655, 9, 'الفيوم ابشواي ابوكساه'),
	(656, 9, 'الفيوم مركز اشواى'),
	(657, 9, 'فلمين موقف علي عامر'),
	(658, 9, 'الفيوم . يوسف الصديق . المشرك عند المكنة'),
	(659, 9, 'طهبار ابشواي الفيوم'),
	(660, 9, 'مركز ابشواي شارع الجمهوريه'),
	(661, 9, 'فيديمين'),
	(662, 9, 'محافظة الفيوم- مركز يوسف الصديق- بريشه الغربيه\\\\01067171890\n مصاريف الشحن 80ج'),
	(663, 9, 'الفيوم الشواشنه'),
	(664, 9, 'الشواشنة بجوار البريد'),
	(665, 9, 'فيديمين'),
	(666, 9, 'فيديمين'),
	(667, 9, 'الفيوم مركز ابشواي بجوار اكزيون'),
	(668, 9, 'قرية بني صالح بجوار مشويات ابو ادهم'),
	(669, 9, 'العنوان الفيوم قرية تلات بجوار مسجد الرحمه'),
	(670, 9, 'الفيوم مركز ابشواي قريه ابو كساه'),
	(671, 9, 'الفيوم سنهور القبليه بجوار كنسيه السيد العذراء مريم'),
	(672, 9, 'فيديمين'),
	(673, 9, 'يوسف الصديق الشواشنه'),
	(674, 9, 'قارين عين سلين امام الجامعيه الزراعيه'),
	(675, 9, 'قارين عين سلين امام الجامعيه الزراعيه'),
	(676, 9, 'قرية ابو دنقاش'),
	(677, 9, 'قرية ابو دنقاش'),
	(678, 9, 'قريه النصاريه'),
	(679, 9, 'قريه النصاريه'),
	(680, 9, 'المشرك قبلي الشوشنه'),
	(681, 9, 'قصر الجبالي'),
	(682, 9, 'ابشواي ابو شنب'),
	(683, 9, 'يوسف الصديق الخرجين'),
	(684, 9, 'كحك بحري'),
	(685, 9, 'قصر الجبالي'),
	(686, 9, 'منشيه فتيح'),
	(687, 9, 'ابشواي ش الجمهوريه بجوار مكتب البريد مخبز محمد علي'),
	(688, 9, 'محافظه الفيوم مركز سنهور القبليه بجوار مسجد الطواحين'),
	(689, 9, 'ابشواي الشواشنه'),
	(690, 9, 'الفيوم مركز الفيوم بني صالح'),
	(691, 9, 'محافظه محافظه الفيوم ابشواي ابوكساه'),
	(692, 9, 'محافظه الفيوم مركز سنهور القبليه بجوار مسجد الطواحين'),
	(693, 9, 'الفيوم ابشواي ع كوبري ابو جنشو معمل الميدان بجوار بنك القاهرة'),
	(694, 9, 'ابوشنب البحريه صيدليه دكتوره عائشه عبد التواب الفيوم'),
	(695, 9, 'الفيوم قريه سنرو'),
	(696, 9, 'الفيوم قريه العجميين مركز ابشواى لمنزل بأسمى بجوار منزل النائب يوسف الشاذلى'),
	(697, 9, 'الفيوم سنهور البحرية بالقرب من بحيرة قارون'),
	(698, 9, 'الفيوم&#x2F;مركز يوسف الصديق&#x2F; قريه بريشه الشرقيه'),
	(699, 9, 'العنوان الفيوم مركز يوسف الصديق قريه النجار'),
	(700, 9, 'الفيوم بجوار مركز سنهور القبليه'),
	(701, 9, 'الفيوم يوسف الصديق المفارق بتاع المركز'),
	(702, 9, 'الفيوم ابشوى النزله الربع'),
	(703, 9, 'مركز ابشواي'),
	(704, 9, 'مركز ابشواي'),
	(705, 9, 'قريه السنباط مركز الفيوم بجوار مسجد التقوي'),
	(706, 9, 'لفيوم/ ابشواي/ أول طريق زيد/ قهوة حسن الاستلام فى وررشه المونتال المهندس محمد'),
	(707, 9, 'الحميديه الجديده'),
	(708, 9, 'الفيوم مركز ابشواى ابو جنشو شارع التحرير بجوار سوبر ماركت التحرير'),
	(709, 9, 'الفيوم مركز ابشواي قرية طبهار عند المعهد الديني'),
	(710, 9, 'ابشواي ابو جنشو شارعه بورر سعيد بجواار مسجد النور'),
	(711, 9, 'مركز ابشواي'),
	(712, 9, 'فيديمين الطريق السياحي لجوار صيدليه الدكتور غيث'),
	(713, 9, 'ابشواي قصر الجبالي'),
	(714, 9, 'مركز ابشواي'),
	(715, 9, 'فيوم قريه قديمن'),
	(716, 9, 'الفيوم.. مركز يوسف الصديق.. الخريجين شارع السجل المدني بجوار البريد.'),
	(717, 9, 'الفيوم قريه بنى صالح الجامع اول طريق بحيره قارون'),
	(718, 9, 'الفيوم سنورس سنهور القبليه'),
	(719, 9, 'محافظه الفيوم قريه فيديمين عند الموقف'),
	(720, 9, 'ابشواي سنرو القبليه'),
	(721, 9, 'الفيوم/بجوار بحيرة قارون/قرية وليدة'),
	(722, 9, 'سنهور القبلية'),
	(723, 9, 'الفيوم مركز ابشواي \nمساكن المطافي محل انتي الاجمل'),
	(724, 9, 'مركز ابشواي قرية ابو عيش على ضفاف بحيرة قارون امام كافيتريا قصر الاليزيه'),
	(725, 9, 'الفيوم سنهور القبلية موقف الفيوم'),
	(726, 9, 'الفيوم فيديمين غرب البلد'),
	(727, 9, 'سنهور الفيله عند المجمع'),
	(728, 9, 'مركز ابشواي ابشواي موقف الفيوم امام مركز مركز القاضي للاشاعات'),
	(729, 9, 'مركز الشواشنة'),
	(730, 9, 'الفيوم مركز ابشواى خلف مسجد الحضانة'),
	(731, 9, 'مركز ابشواي ابشواي موقف الفيوم امام مركز مركز القاضي للاشاعات'),
	(732, 9, 'الفيوم مركز يوسف الصديق عزبة عفيفي'),
	(733, 9, 'الفيوم قارون القرية الاوالي'),
	(734, 9, 'الفيوم. يوسف الصديق.الحامولى'),
	(735, 9, 'زاوية كرداسة مركز الفيوم'),
	(736, 9, 'قريه ثلاث بجوارمسجد الفارق عمر'),
	(737, 9, 'مركز الشوشنه حارت اروبي امام الفرنه'),
	(738, 9, 'الفيوم مركز ابشواي - قرية ابو جنشو - بجوار مدرسة فاطمة الزهراء الاعدادية - منزل ربيع محمود'),
	(739, 9, 'الفيوم أبشواي مركز أبشواي'),
	(740, 9, 'مركز الشوشنه حارت اروبي امام الفرنه'),
	(741, 9, 'الفيوم مركز ابشواي -كحك بحري بجوار صيدليه موده'),
	(742, 9, 'الفيوم /ابشواي/شكشوك'),
	(743, 9, 'الفيوم شارع ابو مدين بجوار المقابر ابوكساه'),
	(744, 9, 'الفيوم بحيره قارون عزبة عبدالقادر موسى'),
	(745, 9, 'الفيوم يوسف الصديق قصر الجبالي منطقة التفتيش بجوار صيدليه دكتور عمرو ادريس'),
	(746, 9, 'نزلة بشير بعد مدرسة الاورمان الخاصة ع طريق ثلاث بلد قبلها مركز الفيوم'),
	(747, 9, 'الشواشنة البريد'),
	(748, 9, 'الفيوم قرية بن صالح بجوار التخريمة محل مشويات آدم'),
	(749, 9, 'العنوان الفيوم ابشواي في ابو جنشوا عند المطحن'),
	(750, 9, 'مركز الشوشنه حارت اروبي امام الفرنه'),
	(751, 9, 'زاويه الكرادسه - فيلا اللواء عبد الغفار - الفيوم,'),
	(752, 9, 'الفيوم مركز سنورس مركز سنهور القبلية بجوار الاسعاف'),
	(753, 9, 'ابشواي امام اوكازيون'),
	(754, 9, 'سنهور القبليه مركز علي صالح'),
	(755, 9, 'انا من ابشواي المنطقه اسمها الرمليه بجوار الجمعيه الخيريه'),
	(756, 9, '‎محافظة الفيوم /مركز ابشواي /قريه كحك قبلي ‎الجامع الكبير'),
	(757, 9, 'القيوم ابشواي ش الجمهوريه المنشيه'),
	(758, 9, 'الفيوم - ابشواى - ابوكساه'),
	(759, 9, 'الفيوم بشويه بوكساه'),
	(760, 9, 'مركز الشوشنه حارت اروبي امام الفرنه'),
	(761, 9, 'يمكن فتح الشحنة /2ق /محافظه الفيوم قريه بني صالح الفيوم'),
	(762, 9, 'سنهور القبليه المفارق عند المسجد الكويتي'),
	(763, 9, 'مركز سنهور'),
	(764, 9, 'قريه سنهور القبليه بجوار فرع فودافون,FAIYUM GOVERNORATE'),
	(765, 9, 'مركز سنهور'),
	(766, 9, 'يوسف الصديق'),
	(767, 9, 'يوسف الصديق'),
	(768, 9, 'يوسف الصديق'),
	(769, 9, 'يوسف الصديق'),
	(770, 9, 'يوسف الصديق'),
	(771, 9, 'يوسف الصديق'),
	(772, 9, 'يوسف الصديق'),
	(773, 9, 'يوسف الصديق'),
	(774, 9, 'شعلان'),
	(775, 9, 'يوسف الصديق'),
	(776, 9, 'شكره امام مدرسه شكره'),
	(777, 9, 'الفيوم النزله ش الوحدة البيطرية رقم 4'),
	(778, 9, 'العنوان /ابشواي بجوار مستشفى الهلال عند موقف الفيوم'),
	(779, 9, 'مركز ابشواي - المنشيه عند المسجد الغربي'),
	(780, 9, 'يوسف الصديق'),
	(781, 9, 'يوسف الصديق'),
	(782, 9, 'الفسوم مركز ابشواي'),
	(783, 9, 'الفيوم ابشوي ابو جنشو شارع الجلاء بجوار المطحن'),
	(784, 9, 'يوسف الصديق قوته'),
	(785, 9, 'الفيوم مركز ابشوى'),
	(786, 9, 'الفيوم قريه فيدمين بجوار عين السيلين'),
	(787, 9, 'مركز يوسف اصديق البلد اوتاه'),
	(788, 9, 'الفيوم السوار الشواشنه'),
	(789, 9, 'الضرب الأخضر منزل بدوى عبد الله'),
	(790, 9, 'قرية شكشوك مركز ابشواى محافظة الفيوم'),
	(791, 9, 'ابشواي مركز يوسف الصديق'),
	(792, 9, 'المشترك القبلي بجوار الكوبرى الغربي مركز يوسف الصديق الفيوم'),
	(793, 9, 'الفيوم / ابشواي / قريه بلونه'),
	(794, 9, 'يوسف الصديق قوته'),
	(795, 9, 'الفيوم /العنوان قريه محافظه الفيوم قرية تلات'),
	(796, 9, 'مركز ابشواي قرية حنا حبيب الفيوم'),
	(797, 9, 'السنباط مركز الفيوم'),
	(798, 9, 'الفيوم مركز سنورس سنهور القبليه طريق عبود'),
	(799, 9, 'العنوان الفيوم ابشواي الشارع الي قبل المستشفى العام'),
	(800, 9, 'يوسف الصديق قوته'),
	(801, 9, 'الفيوم\nمركز يوسف الصديق قرية الحامولي\nعزبت حمزاوي بجوار المقابر'),
	(802, 9, 'سنورس_ مركز سنهور الفيوم'),
	(803, 9, 'مركز يوسف الصديق ، قرية كحك البحرى ، بجوار مركز الشباب'),
	(804, 9, 'بجوار مدرسه الثانوى العامه'),
	(805, 9, 'ابشواي ابو جنشو بجوار مدرسه التجاره');

-- Dumping structure for table orders.sub_centers_history
CREATE TABLE IF NOT EXISTS `sub_centers_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_users_history_users` (`user_id`) USING BTREE,
  CONSTRAINT `sub_centers_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table orders.sub_centers_history: ~0 rows (approximately)

-- Dumping structure for table orders.uid
CREATE TABLE IF NOT EXISTS `uid` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `uid` varchar(50) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 0,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `FK_uid_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.uid: ~1 rows (approximately)
INSERT INTO `uid` (`id`, `uid`, `active`, `user_id`, `created_at`) VALUES
	(19, 'c9306f1735c29356', 1, 27, '2022-12-24 17:37:13');

-- Dumping structure for table orders.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `username` char(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `gender` char(1) NOT NULL DEFAULT '',
  `address` varchar(255) CHARACTER SET utf8 NOT NULL,
  `identy_number` char(255) NOT NULL,
  `Driving_License` char(255) NOT NULL DEFAULT '',
  `bike_license` char(255) NOT NULL DEFAULT '',
  `commision` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `remember_token` char(255) NOT NULL DEFAULT '',
  `rank_id` int(2) NOT NULL,
  `phonep` char(11) NOT NULL,
  `phonew` char(11) NOT NULL,
  `phone3` char(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `FK_users_ranks` (`rank_id`),
  CONSTRAINT `FK_users_ranks` FOREIGN KEY (`rank_id`) REFERENCES `ranks` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.users: ~10 rows (approximately)
INSERT INTO `users` (`id`, `name`, `username`, `password`, `gender`, `address`, `identy_number`, `Driving_License`, `bike_license`, `commision`, `created_at`, `updated_at`, `remember_token`, `rank_id`, `phonep`, `phonew`, `phone3`) VALUES
	(26, 'mahmoud', 'hhetlar121', '$2y$10$QgT.czVTcf3K2mrwF.gkuu79WCOCUXZ3aZo0nmJxbE06AFWTbq39i', 'm', '11', '/storage/26/identy.pdf', '*', '*', 1500, '2022-12-24 19:56:33', '2022-12-24 19:56:33', '', 4, '*', '*', '*'),
	(27, 'mahmoud medhat', 'hetlarhhs@gmail.com', '$2y$10$OR7/oynMY/fwbAqnragHyOObO2pxW4dgwWhTmJfqsNCBZw/j7dPkS', 'm', '*', '/storage/27/identy.pdf', '*', '*', 0, '2022-11-29 14:12:01', '2022-11-29 14:12:01', '', 9, '01118991230', '*', '*'),
	(28, 'محمود طرفايه', '01004091003', '$2y$10$.IXcPepdi8hSRQK1KMVtUefx9trW40RaLFsaS.mlnS/81L4f7gOay', 'm', 'ابكسا ابشواي', '*', '*', '*', 15, '2022-12-10 11:26:06', '2022-12-10 11:26:06', '', 8, '*', '*', '*'),
	(29, 'احمد اشرف', '01211122305', '$2y$10$9mZEDmMhlbgCcjkuu2kOeOYkwFoZCvKXkNrtABX6JWuOSqB2S/nQC', 'm', '*', '*', '*', '*', 15, '2022-12-19 16:37:06', '2022-12-19 16:37:06', '', 8, '*', '*', '*'),
	(30, 'احمد حسين', '01000602092', '$2y$10$PQHNq0MCUeBwbJaFGhWbSOS8WExFnh1dXb2ScgVr.Z6h/y/w46Nvy', 'm', 'طاميه', '*', '*', '*', 15, '2022-12-19 16:37:32', '2022-12-19 16:37:32', '', 8, '*', '*', '*'),
	(31, 'احمد ربيع', '01020021620', '$2y$10$VJ8oOkAKB.BB6Jybatk9zOJe14s/rooyeBu6yfR.6lp1kQlkZfvam', 'm', '*', '*', '*', '*', 15, '2022-12-19 16:37:58', '2022-12-19 16:37:58', '', 8, '*', '*', '*'),
	(32, 'محمد الشيخ', '0103389071', '$2y$10$CDqtsWecEDkMchxwhXSc9.0AnFujsdaeC90rFzSIbapHfenBNjm0O', 'm', '*', '*', '*', '*', 0, '2022-11-28 15:57:40', NULL, '', 8, '*', '*', '*'),
	(33, 'محمد رمضان', '01010783089', '$2y$10$mV0oO6bVckSK4EJPvAWkhOa47ztGGOrx8RZhj7eoSuQeKZSyjuTS6', 'm', '*', '*', '*', '*', 7, '2022-12-19 16:38:30', '2022-12-19 16:38:30', '', 8, '*', '*', '*'),
	(34, 'احمد عبد النبي', '01026249582', '$2y$10$7NEXHzPC8/zwbm.Y/Td1qeqL0VkqflhfRrM1zPUmRIcQyfD2J3WsC', 'm', '*', '*', '*', '*', 20, '2022-12-01 16:36:15', '2022-12-01 16:36:15', '', 9, '*', '*', '*'),
	(43, 'mahmoud medhat', 'hhetlar12100', '$2y$10$qnVlDgym5CIlIyp1XqOkxOUT7MviY/VRPFSI8iYwOGfdyNdw3JUFK', 'm', 'cairo', '*', '*', '*', 15, '2022-12-24 19:54:45', NULL, '', 8, '01148422820', '01148422820', '01148422820');

-- Dumping structure for table orders.users_history
CREATE TABLE IF NOT EXISTS `users_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `action` char(50) NOT NULL,
  `old` varchar(500) DEFAULT NULL,
  `new` varchar(500) DEFAULT NULL,
  `user_id` int(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `FK_users_history_users` (`user_id`),
  CONSTRAINT `FK_users_history_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table orders.users_history: ~8 rows (approximately)
INSERT INTO `users_history` (`id`, `action`, `old`, `new`, `user_id`, `created_at`) VALUES
	(1, 'add', NULL, '[', 27, '2022-12-27 01:05:45'),
	(2, 'add', NULL, '[{"id":43,"name":"mahmoud medhat","username":"hhetlar12100","password":"$2y$10$qnVlDgym5CIlIyp1XqOkxOUT7MviY\\/VRPFSI8iYwOGfdyNdw3JUFK","gender":"m","address":"cairo","identy_number":"*","Driving_License":"*","bike_license":"*","commision":15,"created_at":"2022-12-24 21:54:45","updated_at":null,"remember_token":"","rank_id":8,"phonep":"01148422820","phonew":"01148422820","phone3":"01148422820"}]', 27, '2022-12-27 01:05:45'),
	(3, 'edit', NULL, '[{"id":26,"name":"mahmoud","username":"hhetlar121","password":"$2y$10$QgT.czVTcf3K2mrwF.gkuu79WCOCUXZ3aZo0nmJxbE06AFWTbq39i","gender":"m","address":"11","identy_number":"\\/storage\\/26\\/identy.pdf","Driving_License":"*","bike_license":"*","commision":1500,"created_at":"2022-12-24 21:56:33","updated_at":"2022-12-24 21:56:33","remember_token":"","rank_id":4,"phonep":"*","phonew":"*","phone3":"*"}]', 27, '2022-12-27 01:05:45'),
	(4, 'edit', '[{"id":26,"name":"mahmoud","username":"hhetlar121","password":"$2y$10$QgT.czVTcf3K2mrwF.gkuu79WCOCUXZ3aZo0nmJxbE06AFWTbq39i","gender":"m","address":"11","identy_number":"\\/storage\\/26\\/identy.pdf","Driving_License":"*","bike_license":"*","commision":1500,"created_at":"2022-12-24 21:56:33","updated_at":"2022-12-24 21:56:33","remember_token":"","rank_id":4,"phonep":"*","phonew":"*","phone3":"*"}]', '[{"id":26,"name":"mahmoud","username":"hhetlar121","password":"$2y$10$QgT.czVTcf3K2mrwF.gkuu79WCOCUXZ3aZo0nmJxbE06AFWTbq39i","gender":"m","address":"11","identy_number":"\\/storage\\/26\\/identy.pdf","Driving_License":"*","bike_license":"*","commision":1500,"created_at":"2022-12-24 21:56:33","updated_at":"2022-12-24 21:56:33","remember_token":"","rank_id":4,"phonep":"*","phonew":"*","phone3":"*"}]', 27, '2022-12-27 01:05:45'),
	(5, 'delete', '[{"id":35,"name":"ert","username":"ert","password":"$2y$10$Dlp324smVUiRagMydrS9regnW2WI8JbccQlvJ\\/ioxrcTfIWjxBzNa","gender":"m","address":"*","identy_number":"*","Driving_License":"*","bike_license":"*","commision":9000,"created_at":"2022-11-30 23:29:07","updated_at":"2022-11-30 23:29:07","remember_token":"","rank_id":5,"phonep":"*","phonew":"*","phone3":"*"}]', NULL, 27, '2022-12-27 01:05:45'),
	(6, 'delete', '[{"id":35,"name":"ert","username":"ert","password":"$2y$10$Dlp324smVUiRagMydrS9regnW2WI8JbccQlvJ\\/ioxrcTfIWjxBzNa","gender":"m","address":"*","identy_number":"*","Driving_License":"*","bike_license":"*","commision":9000,"created_at":"2022-11-30 23:29:07","updated_at":"2022-11-30 23:29:07","remember_token":"","rank_id":5,"phonep":"*","phonew":"*","phone3":"*"}]', NULL, 27, '2022-12-27 01:05:45'),
	(7, 'delete', '[{"id":35,"name":"ert","username":"ert","password":"$2y$10$Dlp324smVUiRagMydrS9regnW2WI8JbccQlvJ\\/ioxrcTfIWjxBzNa","gender":"m","address":"*","identy_number":"*","Driving_License":"*","bike_license":"*","commision":9000,"created_at":"2022-11-30 23:29:07","updated_at":"2022-11-30 23:29:07","remember_token":"","rank_id":5,"phonep":"*","phonew":"*","phone3":"*"}]', NULL, 27, '2022-12-27 01:05:45'),
	(8, 'delete', '[{"id":35,"name":"ert","username":"ert","password":"$2y$10$Dlp324smVUiRagMydrS9regnW2WI8JbccQlvJ\\/ioxrcTfIWjxBzNa","gender":"m","address":"*","identy_number":"*","Driving_License":"*","bike_license":"*","commision":9000,"created_at":"2022-11-30 23:29:07","updated_at":"2022-11-30 23:29:07","remember_token":"","rank_id":5,"phonep":"*","phonew":"*","phone3":"*"}]', NULL, 27, '2022-12-27 01:05:45');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
